"""Tests for pipeline data flow fixes (idea: pipeline-data-flow-fixes).

Acceptance criteria verified:

1. **check_pipeline --json** — When GET /api/agent/status-report returns a monitor
   placeholder summary (``Report not yet generated by monitor``), hierarchical output
   must be derived from **pipeline-status + effectiveness** instead of copying the
   placeholder layers (fixes stale/empty Goal data in JSON output).

2. **_build_hierarchical_from_data** — Produces all four layers with execution data
   (running, pending, recent_completed) flowing from pipeline-status and goal metrics
   from effectiveness when provided.

Uses the same httpx mocking pattern as ``test_check_pipeline_hierarchical`` (no live API).
"""

from __future__ import annotations

import io
import json
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

_scripts_dir = str(Path(__file__).resolve().parent.parent / "scripts")
if _scripts_dir not in sys.path:
    sys.path.insert(0, _scripts_dir)

import check_pipeline  # noqa: E402


_PIPELINE_MINIMAL = {
    "running": [],
    "pending": [],
    "recent_completed": [],
    "project_manager": None,
    "attention": {"flags": []},
}

_PLACEHOLDER_STATUS_REPORT = {
    "layer_0_goal": {
        "status": "unknown",
        "summary": "Report not yet generated by monitor",
    },
    "layer_1_orchestration": {"status": "unknown", "summary": ""},
    "layer_2_execution": {"status": "unknown", "summary": ""},
    "layer_3_attention": {"status": "ok", "summary": "No issues"},
}

_EFFECTIVENESS = {
    "goal_proximity": 0.82,
    "throughput": {"completed_7d": 12},
    "success_rate": 0.91,
}


def _mock_httpx_placeholder_report(url: str, **kwargs):
    resp = MagicMock()
    if "/api/agent/pipeline-status" in url:
        resp.status_code = 200
        resp.json.return_value = _PIPELINE_MINIMAL
    elif "/api/agent/status-report" in url:
        resp.status_code = 200
        resp.json.return_value = _PLACEHOLDER_STATUS_REPORT
    elif "/api/agent/effectiveness" in url:
        resp.status_code = 200
        resp.json.return_value = _EFFECTIVENESS
    else:
        resp.status_code = 404
        resp.text = "not found"
        resp.json.side_effect = ValueError("not json")
    return resp


def _run_check_pipeline_json() -> dict:
    with (
        patch.object(sys, "argv", ["check_pipeline.py", "--json"]),
        patch("check_pipeline.httpx.get", side_effect=_mock_httpx_placeholder_report),
        patch(
            "check_pipeline._get_pipeline_process_args",
            return_value={"runner_workers": 5, "pm_parallel": True},
        ),
        patch("sys.stdout", new_callable=io.StringIO) as mock_out,
    ):
        check_pipeline.main()
    return json.loads(mock_out.getvalue())


def test_json_hierarchical_derives_from_pipeline_when_monitor_placeholder_summary():
    """Placeholder monitor report must not appear as Goal layer in --json output."""
    data = _run_check_pipeline_json()
    assert "hierarchical" in data
    h = data["hierarchical"]
    l0 = h["layer_0_goal"]
    assert l0.get("summary") != "Report not yet generated by monitor"
    assert l0.get("goal_proximity") == pytest.approx(0.82)
    assert "12" in str(l0.get("summary", ""))
    assert "91" in str(l0.get("summary", "")) or "91%" in str(l0.get("summary", ""))


def test_json_hierarchical_execution_layer_reflects_pipeline_status_tasks():
    """Layer 2 must carry running / pending / recent_completed from pipeline-status."""
    data = _run_check_pipeline_json()
    h = data["hierarchical"]["layer_2_execution"]
    assert h.get("running") == []
    assert h.get("pending") == []
    assert h.get("recent_completed") == []


def test_build_hierarchical_from_data_flows_goal_and_execution():
    """Direct unit check: merged dict ties effectiveness to layers 0–3."""
    merged = check_pipeline._build_hierarchical_from_data(
        dict(_PIPELINE_MINIMAL),
        dict(_EFFECTIVENESS),
        {"runner_workers": 5, "pm_parallel": False},
    )
    assert merged["layer_0_goal"]["goal_proximity"] == pytest.approx(0.82)
    assert merged["layer_2_execution"]["summary"] == "running=0, pending=0, recent_completed=0"
    assert merged["layer_3_attention"]["summary"] == "No issues"


def test_human_output_skips_placeholder_goal_for_effectiveness():
    """Human hierarchical view must not print placeholder Goal when summary says not yet generated."""
    with (
        patch.object(sys, "argv", ["check_pipeline.py"]),
        patch("check_pipeline.httpx.get", side_effect=_mock_httpx_placeholder_report),
        patch(
            "check_pipeline._get_pipeline_process_args",
            return_value={"runner_workers": 5, "pm_parallel": True},
        ),
        patch("sys.stdout", new_callable=io.StringIO) as mock_out,
    ):
        check_pipeline.main()
    out = mock_out.getvalue()
    assert "Report not yet generated by monitor" not in out
    assert "goal_proximity" in out.lower() or "0.82" in out
