"""Supplementary acceptance tests for spec 036 — check_pipeline hierarchical view.

Covers acceptance criteria not fully isolated in test_check_pipeline_hierarchical.py:
- Goal fallback when status-report is missing or monitor placeholder (effectiveness or message).
- JSON hierarchical structure when status-report defers to built layers from pipeline-status.
- Tasks and Artifacts still sourced from pipeline-status when Goal uses fallback.

Uses mocked HTTP only (no live API).
"""

from __future__ import annotations

import io
import json
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import httpx

_scripts_dir = str(Path(__file__).resolve().parent.parent / "scripts")
if _scripts_dir not in sys.path:
    sys.path.insert(0, _scripts_dir)

import check_pipeline  # noqa: E402

_PIPELINE_STATUS = {
    "running": [
        {
            "id": "t_run",
            "task_type": "impl",
            "model": "openai/gpt-4o-mini",
            "running_seconds": 10,
            "direction": "Implement feature",
        }
    ],
    "pending": [
        {
            "id": "t_pend",
            "task_type": "test",
            "wait_seconds": 5,
            "direction": "Verify",
        }
    ],
    "recent_completed": [
        {
            "id": "t_done",
            "task_type": "impl",
            "duration_seconds": 60,
            "output_len": 900,
            "output_preview": "ok",
        }
    ],
    "project_manager": {"backlog_index": 1, "phase": "implement", "current_task_id": "t_run"},
    "attention": {"flags": []},
}

_EFFECTIVENESS = {
    "goal_proximity": 0.62,
    "throughput": {"completed_7d": 3},
    "success_rate": 0.75,
}

# Monitor has not produced a real goal summary yet (API still returns 200).
_STATUS_PLACEHOLDER = {
    "layer_0_goal": {
        "status": "unknown",
        "summary": "Report not yet generated by monitor",
    },
    "layer_1_orchestration": {"status": "unknown", "summary": ""},
    "layer_2_execution": {},
    "layer_3_attention": {},
}


def _mock_get_factory(status_json: dict | None, status_code: int = 200):
    """status_json None => status-report endpoint errors (treated as no report)."""

    def _mock(url: str, **kwargs):
        r = MagicMock()
        if "/api/agent/pipeline-status" in url:
            r.status_code = 200
            r.json.return_value = _PIPELINE_STATUS
        elif "/api/agent/status-report" in url:
            if status_json is None:
                raise httpx.ConnectError("no status report")
            r.status_code = status_code
            r.json.return_value = status_json
        elif "/api/agent/effectiveness" in url:
            r.status_code = 200
            r.json.return_value = _EFFECTIVENESS
        else:
            r.status_code = 404
            r.text = "not found"
            r.json.side_effect = ValueError("not json")
        return r

    return _mock


def _run_with_mock(mock_fn, *cli_args: str) -> str:
    with (
        patch.object(sys, "argv", ["check_pipeline.py", *cli_args]),
        patch("check_pipeline.httpx.get", side_effect=mock_fn),
        patch(
            "check_pipeline._get_pipeline_process_args",
            return_value={"runner_workers": 5, "pm_parallel": True},
        ),
        patch("sys.stdout", new_callable=io.StringIO) as mock_out,
    ):
        check_pipeline.main()
    return mock_out.getvalue()


def test_036_goal_fallback_from_effectiveness_when_monitor_placeholder():
    """Acceptance: when status-report is placeholder, Goal uses effectiveness; order preserved."""
    stdout = _run_with_mock(
        _mock_get_factory(_STATUS_PLACEHOLDER),
    )
    low = stdout.lower()
    assert "goal (layer 0)" in low
    assert "goal_proximity" in low or "0.62" in stdout
    g = low.index("goal (layer 0)")
    p = low.index("pm / orchestration (layer 1)")
    t = low.index("tasks (layer 2)")
    a = low.index("artifacts (layer 3)")
    assert g < p < t < a


def test_036_goal_message_when_no_effectiveness_and_placeholder_goal():
    """Acceptance: placeholder goal + no effectiveness shows report-not-generated line."""
    def _mock(url: str, **kwargs):
        r = MagicMock()
        if "/api/agent/pipeline-status" in url:
            r.status_code = 200
            r.json.return_value = _PIPELINE_STATUS
        elif "/api/agent/status-report" in url:
            r.status_code = 200
            r.json.return_value = _STATUS_PLACEHOLDER
        elif "/api/agent/effectiveness" in url:
            r.status_code = 503
            r.json.side_effect = ValueError("no json")
        else:
            r.status_code = 404
            r.json.side_effect = ValueError("x")
        return r

    stdout = _run_with_mock(_mock)
    assert "(report not yet generated)" in stdout.lower()


def test_036_json_includes_hierarchical_when_placeholder_triggers_build():
    """Acceptance: --json includes hierarchical from pipeline + effectiveness when monitor placeholder."""
    stdout = _run_with_mock(_mock_get_factory(_STATUS_PLACEHOLDER), "--json")
    data = json.loads(stdout)
    assert "hierarchical" in data
    h = data["hierarchical"]
    assert h["layer_0_goal"]["summary"] != "Report not yet generated by monitor"
    assert "goal_proximity" in h["layer_0_goal"]
    assert "running" in h["layer_2_execution"] or data.get("running")


def test_036_tasks_and_artifacts_present_under_goal_fallback():
    """Acceptance: Tasks and Artifacts still reflect pipeline-status when Goal is fallback."""
    stdout = _run_with_mock(_mock_get_factory(_STATUS_PLACEHOLDER))
    low = stdout.lower()
    assert "t_run" in low or "running" in low
    assert "artifacts (layer 3)" in low
    assert "900" in stdout or "chars" in low


def test_036_status_report_unreachable_uses_effectiveness_for_goal():
    """When GET status-report fails, Goal layer still populated from effectiveness."""
    stdout = _run_with_mock(_mock_get_factory(None))
    assert "goal (layer 0)" in stdout.lower()
    assert "goal_proximity" in stdout.lower() or "0.62" in stdout
