// Generated by web/scripts/generate-locale-manifest.mjs. Do not edit by hand.
import bundle_en from "./en.json";
import bundle_de from "./de.json";
import bundle_es from "./es.json";
import bundle_fr from "./fr.json";
import bundle_id from "./id.json";
import bundle_pt_br from "./pt-br.json";

export const DEFAULT_LOCALE = "en" as const;

export const LOCALES = [
  {
    "code": "en",
    "name": "English",
    "nativeName": "English"
  },
  {
    "code": "de",
    "name": "German",
    "nativeName": "Deutsch"
  },
  {
    "code": "es",
    "name": "Spanish",
    "nativeName": "Español"
  },
  {
    "code": "fr",
    "name": "French",
    "nativeName": "Français"
  },
  {
    "code": "id",
    "name": "Indonesian",
    "nativeName": "Bahasa Indonesia"
  },
  {
    "code": "pt-br",
    "name": "Brazilian Portuguese",
    "nativeName": "Português (Brasil)"
  }
] as const;

export type LocaleCode = (typeof LOCALES)[number]["code"];
export type Locale = (typeof LOCALES)[number];
export type MessageTree = Record<string, unknown>;

export const BUNDLES: Record<LocaleCode, MessageTree> = {
  "en": bundle_en as MessageTree,
  "de": bundle_de as MessageTree,
  "es": bundle_es as MessageTree,
  "fr": bundle_fr as MessageTree,
  "id": bundle_id as MessageTree,
  "pt-br": bundle_pt_br as MessageTree,
};
