// ════════════════════════════════════════════════════════════════════
// MASCHINELL ÜBERSETZT · machine-translated from en.tsx
// Generated by scripts/generate_curated_translations.py via libretranslate.
// JSX structure preserved via placeholder-tag pre/post processing.
// Refinement welcome — replace any line with author-curated prose at
// any time; the locale-router will pick this file up automatically.
// To regenerate: python3 scripts/generate_curated_translations.py \
//                  --slug trimble-glue-layer --target-lang es
// ════════════════════════════════════════════════════════════════════
import Link from "next/link";
import type { PersonProfileContent } from "@/components/people/PersonProfileTemplate";

const content: PersonProfileContent = {
  metadata: {title: "Trimble Client/Server Glue Layer — cadencia independiente, cable-optimal",description: "En Trimble Navigation (Jan 2007 – Oct 2009), construyó la capa de pegamento entre plataformas cliente y servidor. Se combinan múltiples llamadas cliente y múltiples versiones API en un intercambio de cable-optimal, con la pila que vive tanto en el cliente como en la capa de borde del servidor. Los equipos de servidores y clientes podrían evolucionar en cadences independientes sin coordinar cada lanzamiento; la capa de pegamento absorbió las diferencias de versión.",
  },breadcrumbName: "Trimble · Glue cliente/Server",
  hero: {
    background:
      "linear-gradient(135deg, hsl(220 30% 8%), hsl(195 35% 14%) 50%, hsl(80 30% 16%))",
    overlayClass:
      "absolute inset-0 bg-gradient-to-t from-background via-background/85 to-background/30",eyebrow: "Trabajo · Trimble Navigation Limited · Ene 2007 – Oct 2009 · Ingeniero de Software",
    eyebrowClass: "text-[hsl(var(--chart-2))]",name: "Trimble — Client/Server Glue Layer",
    welcome: (
      <p>
        At Trimble Navigation, built the <strong>glue layer</strong>{" "}
        sitting on both the client and the server edge — the
        load-bearing piece that let the two sides evolve on{" "}
        <em>independent cadences</em>, with multiple client calls and
        multiple API versions combined into one wire-optimal exchange.
        Server and client teams could ship on their own rhythm without
        coordinating each release; the glue absorbed the version
        differences and the round-trip optimisation. Neither team
        had to think about wire shape.
      </p>
    ),
  },
  facts: [
    {label: "Era",value: "Trimble Navigation Limited · enero 2007 – octubre 2009 · 2 años 10 meses · Ingeniero de Software" },
    {label: "Substrate",value: "Cross-platform — lado cliente corrió en el campo en el posicionamiento de hardware; lado servidor en la nube / infraestructura corporativa"
    },
    {label: "Función",
      value: (
        <>
          One stack on both edges — client glue + server glue —
          carrying version translation, call coalescing, and wire
          shaping; the substrate the team-on-team coordination
          problem dissolved into.
        </>
      ),
    },
    {label: "Condena",
      value: (
        <>
          <em>Coupling kills cadence.</em> Two teams cannot ship
          independently if their wire contract requires them to. The
          glue layer was the architectural answer: <em>let each team
          author against its current self, and let the glue absorb
          the version skew.</em>
        </>
      ),
    },
    {label: "Líneas de avance",
      value: (
        <>
          The same shape is now what the{" "}
          <Link href="/people/coherence-network" className="hover:text-primary">Coherence Network</Link>
          's API + adapter layer carries: one OpenAPI contract, multiple
          client surfaces (web · CLI · MCP · agent harnesses) all
          decoupled from API-version cadence by the same kind of glue.
        </>
      ),
    },
  ],
  noteFromBody: {eyebrow: "¿Por qué la capa de pegamento importaba",
    body: (
      <p>
        Without it, every API change from the server team meant a
        synchronised release with the client team. With it, the
        client team kept shipping for whatever wire version they
        already understood, the server team kept shipping for
        whatever wire version <em>they</em> already understood, and
        the glue layer translated between them. The architecture
        decoupled cadence from contract. Two teams could each move
        at the speed they could move at, instead of at the speed of
        the slower one.
      </p>
    ),
  },
  articles: [
    {
      kind: "narrative",heading: "Dos bordes de la misma pila",
      body: (
        <>
          <p>
            The architectural choice that let the layer absorb its
            workload: the glue ran <em>twice</em>, once on the client
            edge and once on the server edge, with a shared codebase
            describing how each side translated. From either team's
            perspective the glue was a library they linked against;
            from the wire's perspective it was a contract that always
            framed calls in the optimal shape regardless of which
            version either team was currently authoring against.
          </p>
          <figure className="my-6 rounded-xl border border-border/40 bg-card/30 p-5">
            <svg viewBox="0 0 720 320" className="w-full h-auto" role="img" aria-labelledby="trimble-glue-title">
              <title id="trimble-glue-title">Trimble client/server glue layer architecture</title>
              <g fontFamily="ui-sans-serif,system-ui" fontSize="12">
                {/* Client side */}
                <text x="170" y="30" fill="hsl(195 80% 80%)" fontSize="13" textAnchor="middle">Client side</text>
                <rect x="60" y="40" width="220" height="44" rx="8" fill="hsl(220 25% 18%)" stroke="hsl(195 60% 60%)" />
                <text x="170" y="62" textAnchor="middle" fill="hsl(195 80% 82%)" fontSize="12">Client app — version Cv</text>
                <text x="170" y="78" textAnchor="middle" fill="hsl(195 50% 70%)" fontSize="10">authors against current client API</text>

                <line x1="170" y1="84" x2="170" y2="100" stroke="hsl(220 30% 60%)" strokeWidth="1.2" />

                <rect x="60" y="100" width="220" height="80" rx="8" fill="hsl(140 35% 16%)" stroke="hsl(140 70% 60%)" strokeWidth="2" />
                <text x="170" y="124" textAnchor="middle" fill="hsl(140 90% 85%)" fontSize="12">Client glue · edge layer</text>
                <text x="80" y="142" fill="hsl(140 60% 75%)" fontSize="10">· version translation (Cv → Sv)</text>
                <text x="80" y="156" fill="hsl(140 60% 75%)" fontSize="10">· call coalescing into one trip</text>
                <text x="80" y="170" fill="hsl(140 60% 75%)" fontSize="10">· response splitting back to caller</text>

                {/* Wire */}
                <line x1="280" y1="140" x2="440" y2="140" stroke="hsl(40 80% 60%)" strokeWidth="2" />
                <rect x="300" y="126" width="120" height="28" rx="14" fill="hsl(40 50% 18%)" stroke="hsl(40 80% 60%)" />
                <text x="360" y="144" textAnchor="middle" fill="hsl(40 90% 85%)" fontSize="11">wire · 1 round-trip</text>

                {/* Server side */}
                <text x="570" y="30" fill="hsl(280 70% 80%)" fontSize="13" textAnchor="middle">Server side</text>
                <rect x="440" y="40" width="220" height="44" rx="8" fill="hsl(220 25% 18%)" stroke="hsl(280 60% 65%)" />
                <text x="550" y="62" textAnchor="middle" fill="hsl(280 80% 82%)" fontSize="12">Server app — version Sv</text>
                <text x="550" y="78" textAnchor="middle" fill="hsl(280 50% 70%)" fontSize="10">authors against current server API</text>

                <line x1="550" y1="84" x2="550" y2="100" stroke="hsl(220 30% 60%)" strokeWidth="1.2" />

                <rect x="440" y="100" width="220" height="80" rx="8" fill="hsl(140 35% 16%)" stroke="hsl(140 70% 60%)" strokeWidth="2" />
                <text x="550" y="124" textAnchor="middle" fill="hsl(140 90% 85%)" fontSize="12">Server glue · edge layer</text>
                <text x="460" y="142" fill="hsl(140 60% 75%)" fontSize="10">· call splitting (1 wire → N calls)</text>
                <text x="460" y="156" fill="hsl(140 60% 75%)" fontSize="10">· version translation (Sv ← incoming)</text>
                <text x="460" y="170" fill="hsl(140 60% 75%)" fontSize="10">· response coalescing for the trip</text>

                {/* Bottom: shared codebase */}
                <rect x="220" y="230" width="280" height="60" rx="8" fill="hsl(220 25% 14%)" stroke="hsl(40 60% 55%)" strokeDasharray="3,3" />
                <text x="360" y="252" textAnchor="middle" fill="hsl(40 80% 80%)" fontSize="12">Shared glue codebase</text>
                <text x="360" y="270" textAnchor="middle" fill="hsl(40 50% 75%)" fontSize="10">version-translation rules · wire-shape contract</text>
                <text x="360" y="284" textAnchor="middle" fill="hsl(40 50% 75%)" fontSize="10">deployed on both edges from one source</text>

                <line x1="170" y1="180" x2="220" y2="260" stroke="hsl(40 50% 55%)" strokeWidth="0.8" strokeDasharray="2,3" />
                <line x1="550" y1="180" x2="500" y2="260" stroke="hsl(40 50% 55%)" strokeWidth="0.8" strokeDasharray="2,3" />
              </g>
            </svg>
            <figcaption className="text-xs text-muted-foreground mt-3 text-center">
              Two edge layers, one shared codebase. The client app
              authors against its current API; the server app
              authors against its current API; the glue layers
              between them absorb the version skew and shape the
              wire into one optimal round-trip.
            </figcaption>
          </figure>
        </>
      ),
    },
    {
      kind: "panel",
      variant: "warm",eyebrow: "Lo que significaba \"wire-optimal\"",heading: "Múltiples llamadas a una ida y vuelta",
      body: (
        <>
          <p>
            A naive client makes N independent API calls and pays N
            network round-trips. The glue layer's coalescing job:
            watch the call pattern from the client app, recognise
            when several calls are batched into a logical unit, fold
            them into a single wire request, dispatch to the server,
            then split the response so each call returned to its
            caller as if it had been independent.
          </p>
          <p>
            The trade-off the layer mediated:{" "}
            <strong>application-team ergonomics versus wire cost</strong>.
            Naturally written client code makes lots of small calls;
            wire-optimal protocols want one big bundle. Without the
            glue, every client call site had to be wire-aware; with
            it, neither team had to think about the wire at all. The
            glue made the trade-off invisible to both sides.
          </p>
          <p>
            This is the same posture, in 2007, that GraphQL would
            commit to for completely different reasons in 2015 —
            "let the client describe its data shape; let the server
            assemble the optimal response in one trip." Trimble's
            glue layer reached the same architectural answer through
            a different door (positioning hardware constrained the
            client side; the server side had to absorb the
            complexity).
          </p>
        </>
      ),
    },
    {
      kind: "narrative",heading: "Cadence como una preocupación arquitectónica de primera clase",
      body: (
        <>
          <p>
            The conviction at the heart of this work: <em>two teams
            should not have their release cadence coupled to a wire
            contract</em>. If shipping a server feature requires the
            client team to ship the same week, neither team can move
            at its true speed. The slower team becomes the rate limit
            for both.
          </p>
          <p>
            The glue layer's contract was therefore not "the current
            API" but "the set of API versions either side might be
            running, and the translations between them." When the
            server team added a new field, the glue layer learned to
            translate calls from old-client-version to new-server-
            version and vice versa. When the client team added a new
            call, the glue layer learned to break that call apart for
            servers that hadn't yet adopted it. Both sides kept
            shipping, on their own rhythm, into a wire that was always
            current with whichever side was further ahead.
          </p>
          <p>
            The same conviction holds in the{" "}
            <Link href="/people/coherence-network" className="text-primary hover:underline">
              Coherence Network
            </Link>
            's design today. The web client and the API ship through
            independent CI runs; the OpenAPI contract is generated
            from FastAPI's source of truth and the TypeScript client
            adapts. Either side can land a change without breaking
            the other; the substrate absorbs version differences. The
            shape Trimble committed to in 2007 is still the right
            shape twenty years on.
          </p>
        </>
      ),
    },
    {
      kind: "panel",
      variant: "cool",eyebrow: "Lineage of decoupling",heading: "Regreso a través de línea al pensamiento de 7 capas",
      body: (
        <p>
          The deepest reading: this is the same conviction the{" "}
          <Link href="/people/schindler-hc11-protocol" className="text-primary hover:underline">
            Schindler 7-layer ISO/OSI work
          </Link>
          {" "}committed to thirty-six years earlier — every layer is
          addressable, every layer does exactly its job, no layer
          collapses into another. At Trimble the conviction landed at
          the application-protocol layer: the client and server were
          two layers, the glue was a layer between them with its own
          discipline, and the wire was a layer below that with its
          own constraints. Each layer authored against its own job,
          not the layers around it. The architecture survives at every
          altitude where this body has applied it.
        </p>
      ),
    },
  ],
  footer: (
    <p>
      Company:{" "}
      <Link href="https://en.wikipedia.org/wiki/Trimble_Inc." target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
        Trimble (Wikipedia)
      </Link>
      {" · "}
      <Link href="https://www.trimble.com" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
        trimble.com
      </Link>
      . Source code is internal to Trimble; what lives here is the
      architectural shape and the design rationale. Urs is invited
      to refine technical detail through the Refine doorway below.
    </p>
  ),
};

export default content;
