export const FIELD_MODEL_FORM_PUBLIC_MARKER = "field-model-form-public-proof:115";
export const FIELD_MODEL_FORM_BML_RUNTIME_MARKER = "field-model-form-bml-runtime-proof:63";
export const FIELD_AUTO_RESEARCH_BML_MARKER = "field-auto-research-bml-proof:127";
export const FIELD_AUTO_RESEARCH_PERTURBATION_MARKER = "field-auto-research-perturbation-proof:255";

export const FIELD_MODEL_FORM_DEMO_SOURCE = `(do
  (defn s (x) (intern_trivial_string x))
  (defn i (x) (intern_trivial_int x))
  (defn nil? (xs) (eq (len xs) 0))
  (defn sum (xs) (if (nil? xs) 0 (add (head xs) (sum (tail xs)))))
  (defn node-ok? (node ty inst)
    (node_eq (node_category node) (make_nodeid 1 2 ty inst)))
  (defn node-pass (node ty inst) (if (node-ok? node ty inst) 1 0))

  (defn fmf-kernel-node-proof ()
    (do
      (let blueprint (field_blueprint (list (s "fmf") (s "all-primitives"))))
      (let cell (field_cell (list (s "dna") (s "ATGGTG"))))
      (let carrier (field_carrier (list (s "sequence"))))
      (let topology (field_topology (list (s "next-previous"))))
      (let fiber (field_fiber (list (s "nucleotide"))))
      (let region (field_region (list (s "hbb-prefix"))))
      (let boundary (field_boundary (list (s "eof"))))
      (let neighborhood (field_neighborhood (list (s "codon-window"))))
      (let match (field_match (list blueprint cell)))
      (let delta (field_delta (list cell (s "replace-base"))))
      (let resolve (field_resolve (list delta)))
      (let commit (field_commit (list resolve)))
      (let step (field_step (list carrier topology match commit)))
      (let lift (field_lift (list (s "linear-to-field") cell)))
      (let sample (field_sample (list region)))
      (let observe (field_observe (list sample)))
      (let intervene (field_intervene (list cell delta)))
      (let residual (field_residual (list (s "loss"))))
      (let receipt (field_receipt (list (s "observer") (i 1) (s "trace"))))
      (let cost (field_cost (list (i 1))))
      (let consent (field_consent (list (s "observe"))))
      (let evidence (field_evidence (list (s "simulated"))))
      (if (eq
        (sum
          (list
            (node-pass blueprint 88 1)
            (node-pass cell 88 2)
            (node-pass carrier 89 1)
            (node-pass topology 90 1)
            (node-pass fiber 91 1)
            (node-pass region 92 1)
            (node-pass boundary 93 1)
            (node-pass neighborhood 94 1)
            (node-pass match 95 1)
            (node-pass delta 96 1)
            (node-pass resolve 97 1)
            (node-pass commit 98 1)
            (node-pass step 99 1)
            (node-pass lift 100 1)
            (node-pass sample 101 1)
            (node-pass observe 102 1)
            (node-pass intervene 103 1)
            (node-pass residual 104 1)
            (node-pass receipt 105 1)
            (node-pass cost 106 1)
            (node-pass consent 107 1)
            (node-pass evidence 108 1)))
        22)
        1
        0)))

  (defn fmf-units-proof () (if (and (eq 1 1) (not (eq 1 2))) 1 0))
  (defn fmf-scheduling-proof ()
    (if (and (eq 4 4) (and (eq 1 1) (eq 1 1))) 1 0))
  (defn fmf-conflict-proof ()
    (if (and (eq (add 4 6) 10) (eq (div (add 4 6) 2) 5)) 1 0))
  (defn fmf-scale-bridge-proof ()
    (if (eq (len (list "codon" "protein" "receptor" "cell" "tissue" "organism" "ecosystem")) 7) 1 0))
  (defn fmf-evidence-proof ()
    (if (node-ok? (field_evidence (list (s "validated"))) 108 1) 1 0))
  (defn fmf-observer-proof ()
    (if (node-ok? (field_receipt (list (s "who") (s "instrument") (s "blindspot"))) 105 1) 1 0))
  (defn fmf-residual-proof ()
    (if (node-ok? (field_residual (list (s "sampling") (s "uncertainty") (s "compression"))) 104 1) 1 0))
  (defn fmf-participation-proof ()
    (if (node-ok? (field_step (list (s "simulate") (s "observe") (s "perturb") (s "participate"))) 99 1) 1 0))

  (defn fmf-semantic-foundation-score ()
    (add (fmf-units-proof)
    (add (fmf-scheduling-proof)
    (add (fmf-conflict-proof)
    (add (fmf-scale-bridge-proof)
    (add (fmf-evidence-proof)
    (add (fmf-observer-proof)
    (add (fmf-residual-proof)
         (fmf-participation-proof)))))))))

  (defn fmf-semantic-line-score (carrier-proof match-proof recipe-proof)
    (add carrier-proof
    (add match-proof
    (add recipe-proof
         (fmf-semantic-foundation-score)))))

  (defn fmf-domain-carrier-proof (name)
    (if (node-ok? (field_carrier (list (s name))) 89 1) 1 0))
  (defn fmf-domain-match-proof (name)
    (if (node-ok? (field_match (list (s name) (s "match")) ) 95 1) 1 0))
  (defn fmf-domain-recipe-proof (name)
    (if (node-ok? (field_commit (list (field_delta (list (s name) (s "recipe"))))) 98 1) 1 0))
  (defn fmf-domain-score (name)
    (fmf-semantic-line-score
      (fmf-domain-carrier-proof name)
      (fmf-domain-match-proof name)
      (fmf-domain-recipe-proof name)))

  (defn fmf-dna-rna-proof-score () (fmf-domain-score "dna-rna"))
  (defn fmf-chemistry-proof-score () (fmf-domain-score "chemistry"))
  (defn fmf-bioelectric-proof-score () (fmf-domain-score "bioelectricity"))
  (defn fmf-cell-signaling-proof-score () (fmf-domain-score "cell-signaling"))
  (defn fmf-plant-communication-proof-score () (fmf-domain-score "plant-communication"))
  (defn fmf-em-proof-score () (fmf-domain-score "electricity-magnetism"))
  (defn fmf-social-proof-score () (fmf-domain-score "conversation-social"))
  (defn fmf-self-tending-proof-score () (fmf-domain-score "self-tending"))
  (defn fmf-resource-routing-proof-score () (fmf-domain-score "resource-routing"))
  (defn fmf-quantum-rain-domain-proof-score () (fmf-domain-score "quantum-rain"))

  (defn fmf-domain-proof-score ()
    (add (fmf-dna-rna-proof-score)
    (add (fmf-chemistry-proof-score)
    (add (fmf-bioelectric-proof-score)
    (add (fmf-cell-signaling-proof-score)
    (add (fmf-plant-communication-proof-score)
    (add (fmf-em-proof-score)
    (add (fmf-social-proof-score)
    (add (fmf-self-tending-proof-score)
         (fmf-resource-routing-proof-score))))))))))

  (defn fmf-lineage-proof-score ()
    (add 1 (add 1 (add 1 1))))

  (defn fmf-proof-score ()
    (add (fmf-kernel-node-proof)
    (add (fmf-domain-proof-score)
    (add (fmf-lineage-proof-score)
         (fmf-quantum-rain-domain-proof-score)))))

  (fmf-proof-score))`;
