import Image from "next/image";
import Link from "next/link";
import {
  displayName,
  inlineMarkdownToHtml,
  storyImagePath,
} from "@/lib/vision-utils";

/**
 * Renders story_content markdown into JSX blocks.
 *
 * Handles: ## headings, ### subheadings, > blockquotes,
 * ![caption](visuals:prompt) inline images (as static files),
 * - list items, → cross-references, paragraphs with bold/italic/links.
 *
 * Inline story images resolve to /visuals/generated/{conceptId}-story-{N}.jpg
 * (pre-generated by scripts/generate_visuals.py). No runtime Pollinations dependency.
 */
export function StoryContent({
  content,
  conceptId,
  nameMap,
}: {
  content: string;
  conceptId: string;
  nameMap: Record<string, string>;
}) {
  let storyVisualIndex = 0;

  // Strip the "## Connected Frequencies" section from story content —
  // the graph-backed ConnectedConcepts section below the story is the
  // single source of truth for connected concepts. Rendering the
  // markdown cross-refs too would duplicate the "Connected Frequencies"
  // heading and show stale/hand-written links alongside live graph edges.
  const connectedIdx = content.search(/^##\s+Connected\s+Frequencies/im);
  const cleanContent = connectedIdx >= 0 ? content.slice(0, connectedIdx).trimEnd() : content;

  return (
    <div className="mb-12 max-w-3xl space-y-6">
      {cleanContent.split("\n\n").map((block, i) => {
        const trimmed = block.trim();
        if (!trimmed) return null;

        // # Top-level heading — skip it, the page already shows the title
        if (trimmed.startsWith("# ") && !trimmed.startsWith("## ")) {
          return null;
        }

        // ## Heading (may include list items if no blank line follows)
        if (trimmed.startsWith("## ") || trimmed.startsWith("### ")) {
          const isH3 = trimmed.startsWith("### ");
          const lines = trimmed.split("\n");
          const headingText = lines[0].slice(isH3 ? 4 : 3);
          const rest = lines.slice(1).filter((l: string) => l.trim()).join("\n");

          if (!rest) {
            return isH3
              ? <h3 key={i} className="text-lg font-light text-stone-400 pt-4 pb-1">{headingText}</h3>
              : <h2 key={i} className="text-2xl font-light text-stone-300 pt-8 pb-2">{headingText}</h2>;
          }

          // Heading with attached list items (e.g. ## Resources\n- item1\n- item2)
          const listItems = rest.split("\n").filter((l: string) => l.trim().startsWith("- "));
          return (
            <div key={i}>
              {isH3
                ? <h3 className="text-lg font-light text-stone-400 pt-4 pb-2">{headingText}</h3>
                : <h2 className="text-2xl font-light text-stone-300 pt-8 pb-2">{headingText}</h2>
              }
              {listItems.length > 0 && (
                <ul className="space-y-2 pl-4">
                  {listItems.map((item: string, j: number) => (
                    <li key={j} className="text-sm text-stone-400 leading-relaxed list-disc"
                      dangerouslySetInnerHTML={{ __html: inlineMarkdownToHtml(item.slice(2).trim()) }}
                    />
                  ))}
                </ul>
              )}
              {listItems.length === 0 && (
                <p className="text-base text-stone-400 leading-relaxed"
                  dangerouslySetInnerHTML={{ __html: inlineMarkdownToHtml(rest) }}
                />
              )}
            </div>
          );
        }
        // > Blockquote
        if (trimmed.startsWith("> ")) {
          return (
            <blockquote key={i} className="border-l-2 border-amber-500/30 pl-4 text-stone-400 italic leading-relaxed">
              {trimmed.slice(2)}
            </blockquote>
          );
        }
        // ![caption](visuals:prompt) — inline story visual (static file)
        const visualMatch = trimmed.match(/^!\[([^\]]*)\]\(visuals:([^)]+)\)$/);
        if (visualMatch) {
          const caption = visualMatch[1];
          const imgPath = storyImagePath(conceptId, storyVisualIndex);
          storyVisualIndex++;
          return (
            <figure key={i} className="py-4">
              <div className="relative aspect-[16/9] rounded-xl overflow-hidden bg-stone-800/50">
                <Image
                  src={imgPath}
                  alt={caption}
                  fill
                  className="object-cover"
                  sizes="(max-width: 768px) 100vw, 768px"
                  unoptimized
                />
              </div>
              <figcaption className="text-xs text-stone-600 mt-2 italic">{caption}</figcaption>
            </figure>
          );
        }
        // - List items
        if (trimmed.startsWith("- ")) {
          const items = trimmed.split("\n").filter((l: string) => l.trim().startsWith("- "));
          return (
            <ul key={i} className="space-y-2 pl-4">
              {items.map((item: string, j: number) => (
                <li key={j} className="text-sm text-stone-400 leading-relaxed list-disc"
                  dangerouslySetInnerHTML={{ __html: inlineMarkdownToHtml(item.slice(2).trim()) }}
                />
              ))}
            </ul>
          );
        }
        // → Cross-references (linked pills): → lc-xxx, lc-yyy
        if (trimmed.startsWith("\u2192 ")) {
          const refs = trimmed.slice(2).split(",").map((r: string) => r.trim()).filter(Boolean);
          return (
            <div key={i} className="flex flex-wrap gap-2 pt-4">
              <span className="text-xs text-stone-600">Connected:</span>
              {refs.map((ref: string) => (
                <Link key={ref} href={`/vision/${ref}`}
                  className="text-xs px-2 py-1 rounded-full border border-stone-700/30 text-stone-500 hover:text-amber-300/70 hover:border-amber-500/20 transition-colors">
                  {displayName(ref, nameMap)}
                </Link>
              ))}
            </div>
          );
        }
        // Mixed paragraph + list items (prose followed by "- " lines)
        const blockLines = trimmed.split("\n");
        const firstListIdx = blockLines.findIndex((l: string) => l.trim().startsWith("- "));
        if (firstListIdx > 0) {
          const proseLines = blockLines.slice(0, firstListIdx).join("\n").trim();
          const listItems = blockLines.slice(firstListIdx).filter((l: string) => l.trim().startsWith("- "));
          return (
            <div key={i}>
              {proseLines && (
                <p className="text-base text-stone-400 leading-relaxed mb-3"
                  dangerouslySetInnerHTML={{ __html: inlineMarkdownToHtml(proseLines) }}
                />
              )}
              <ul className="space-y-2 pl-4">
                {listItems.map((item: string, j: number) => (
                  <li key={j} className="text-sm text-stone-400 leading-relaxed list-disc"
                    dangerouslySetInnerHTML={{ __html: inlineMarkdownToHtml(item.trim().slice(2).trim()) }}
                  />
                ))}
              </ul>
            </div>
          );
        }
        // Regular paragraph
        return (
          <p key={i} className="text-base text-stone-400 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: inlineMarkdownToHtml(trimmed) }}
          />
        );
      })}
    </div>
  );
}
