"""Generated by form/form-stdlib/emits/python-native.fk from python-bmf.fk.
Do not edit by hand — re-emit via form/scripts/emit_native_python.sh.

PyBmfCategory mirrors PY-BMF-* in python-bmf.fk; py_* helpers
build leaf source atoms scanned from Python text.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import IntEnum

from .sdk import NodeID, SourceSpan


class PyBmfCategory(IntEnum):
    IMPORT = 501
    FROM_IMPORT = 502
    DEF = 503
    CLASS = 504
    ASSIGN = 505
    RETURN = 506
    RAISE = 507
    PASS = 508
    IF = 509
    WHILE = 510
    FOR = 511
    CALL = 512
    INT = 513
    STRING = 514
    IDENT = 515
    ATTR = 516
    METHOD_CALL = 517
    LIST = 518
    DICT = 519
    ANNOTATED = 520
    AUG_ASSIGN = 521
    BINOP = 522
    MODULE = 523
    BOOL = 524
    NONE = 525
    UNARY = 526
    COMPARE = 527
    BOOL_OP = 528
    SUBSCRIPT = 529
    SLICE = 530
    TUPLE = 531
    SET = 532
    LAMBDA = 533
    AWAIT = 534
    YIELD = 535
    BREAK = 536
    CONTINUE = 537
    GLOBAL = 538
    NONLOCAL = 539
    DEL = 540
    ASSERT = 541
    WITH = 542
    TRY = 543
    ASYNC_DEF = 544
    DECORATOR = 545
    ASYNC_FOR = 546
    ASYNC_WITH = 547
    IF_ELSE = 548
    ELIF = 549
    RAISE_FROM = 550
    IMPORT_STAR = 551
    IMPORT_MANY = 552
    EXCEPT_AS = 553
    MATCH = 554
    CASE = 555
    COMP = 556
    GENEXP = 557
    KWARG = 558
    STARARG = 559
    DEFAULT = 560
    TYPED_PARAM = 561
    RET_ANN = 562
    WALRUS = 563
    FLOAT = 564
    BYTES = 565
    ELLIPSIS = 566
    ATTR_ASSIGN = 567
    SUB_ASSIGN = 568
    UNPACK = 569
    FSTRING = 570
    IFEXP = 571
    SETCOMP = 572
    YIELD_FROM = 573
    MATCH_AS = 574

    def nodeid(self) -> NodeID:
        return NodeID(1, 2, 99, int(self))


@dataclass
class BmfAtom:
    kind: str
    value: str
    span: SourceSpan = field(default_factory=SourceSpan.empty)

    def __repr__(self) -> str:
        return f"{self.kind}({self.value!r})"


def py_keyword(value, span=None):
    return BmfAtom("py-keyword", value, span or SourceSpan.empty())

def py_name(value, span=None):
    return BmfAtom("py-name", value, span or SourceSpan.empty())

def py_op(value, span=None):
    return BmfAtom("py-op", value, span or SourceSpan.empty())

def py_int(value, span=None):
    return BmfAtom("py-int", value, span or SourceSpan.empty())

def py_float(value, span=None):
    return BmfAtom("py-float", value, span or SourceSpan.empty())

def py_string(value, span=None):
    return BmfAtom("py-string", value, span or SourceSpan.empty())

def py_bytes(value, span=None):
    return BmfAtom("py-bytes", value, span or SourceSpan.empty())

def py_fstring(value, span=None):
    return BmfAtom("py-fstring", value, span or SourceSpan.empty())

def py_tstring(value, span=None):
    return BmfAtom("py-tstring", value, span or SourceSpan.empty())

def py_layout(value, span=None):
    return BmfAtom("py-layout", value, span or SourceSpan.empty())

PYTHON_KEYWORDS: tuple = ("import", "from", "as", "def", "return", "class", "pass", "if", "else", "elif", "while", "for", "in", "with", "async", "await", "try", "except", "finally", "raise", "True", "False", "None", "not", "and", "or", "yield", "global", "nonlocal", "del", "assert", "match", "case", "lambda", "is", "type",)
PYTHON_OPERATORS: tuple = ("**=", "//=", ">>=", "<<=", ":=", "==", "!=", "<=", ">=", "->", "@=", "+=", "-=", "*=", "/=", "%=", "&=", "|=", "^=", "**", "//", "<<", ">>", "...", "(", ")", "[", "]", "{", "}", ",", ":", ".", ";", "@", "=", "+", "-", "*", "/", "%", "&", "|", "^", "~", "<", ">", "!",)

