#!/usr/bin/env python3
"""Generate the kernel-resident bp lookup table for all three Form kernels.

`bp "name"` resolves a Blueprint name to its NodeID. To make it universally
available — no `form-ontology-loader.fk` prelude required — each kernel embeds
this table and registers `bp` as a native. The table is generated from the two
authored sources (form-ontology.json categories/primitives + blueprint-registry.json),
so all three kernels carry byte-identical data and stay in parity by construction.

Emits one source file per kernel (committed; regenerate when either JSON changes,
wired into validate.sh's build step and the post-merge hook):
  form/form-kernel-go/bp_table.go      — var bpTable map[string][4]uint32
  form/form-kernel-rust/src/bp_table.rs — pub static BP_ENTRIES: &[(&str,[u32;4])]
  form/form-kernel-ts/src/bp_table.ts   — export const BP_TABLE: Record<string,[…]>

A name maps to one coordinate; the kernel-owned categories/primitives win over
the registry on the rare name collision. Canonical names and historical aliases
both resolve, so JSON-OBJECT and HTML-OBJ reach the same NodeID.

Usage: python3 scripts/gen_bp_table.py
"""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
STDLIB = ROOT / "form" / "form-stdlib"
ONTOLOGY = STDLIB / "form-ontology.json"
REGISTRY = STDLIB / "blueprint-registry.json"
GO = ROOT / "form" / "form-kernel-go" / "bp_table.go"
RS = ROOT / "form" / "form-kernel-rust" / "src" / "bp_table.rs"
TS = ROOT / "form" / "form-kernel-ts" / "src" / "bp_table.ts"


def build_table() -> dict[str, tuple]:
    """name → (pkg, level, type, inst). Kernel-owned shapes first (they win)."""
    table: dict[str, tuple] = {}

    def add(name, coord):
        if name not in table:           # first writer wins (ontology before registry)
            table[name] = coord

    onto = json.loads(ONTOLOGY.read_text())
    for items in (onto.get("categories", []), onto.get("primitives", [])):
        for r in items:
            add(r["name"], (1, 2, r["type"], r["inst"]))
    for r in json.loads(REGISTRY.read_text()).get("blueprints", []):
        coord = (r.get("pkg", 1), r.get("level", 2), r.get("type", 99), r["inst"])
        add(r["name"], coord)
        for alias in r.get("aliases", []):
            add(alias, coord)
    return dict(sorted(table.items()))


HEADER = ("// Code generated by scripts/gen_bp_table.py from form-ontology.json +\n"
          "// blueprint-registry.json. DO NOT EDIT. Regenerate after either changes.\n")


def emit_go(t: dict[str, tuple]) -> str:
    lines = [HEADER, "package main\n", "var bpTable = map[string][4]uint32{"]
    for name, (p, l, ty, i) in t.items():
        lines.append(f'\t{json.dumps(name)}: {{{p}, {l}, {ty}, {i}}},')
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_rust(t: dict[str, tuple]) -> str:
    lines = [HEADER.replace("//", "//"),
             "pub static BP_ENTRIES: &[(&str, [u32; 4])] = &["]
    for name, (p, l, ty, i) in t.items():
        lines.append(f'    ({json.dumps(name)}, [{p}, {l}, {ty}, {i}]),')
    lines.append("];")
    return "\n".join(lines) + "\n"


def emit_ts(t: dict[str, tuple]) -> str:
    lines = [HEADER,
             "export const BP_TABLE: Record<string, [number, number, number, number]> = {"]
    for name, (p, l, ty, i) in t.items():
        lines.append(f'  {json.dumps(name)}: [{p}, {l}, {ty}, {i}],')
    lines.append("};")
    return "\n".join(lines) + "\n"


def _write_if_changed(path: pathlib.Path, content: str) -> bool:
    """Write only when content differs — keeps mtimes stable so validate.sh's
    `kernel source newer than binary?` staleness check doesn't rebuild on every
    run."""
    if path.exists() and path.read_text() == content:
        return False
    path.write_text(content)
    return True


def main() -> int:
    t = build_table()
    changed = [p.name for p, c in ((GO, emit_go(t)), (RS, emit_rust(t)), (TS, emit_ts(t)))
               if _write_if_changed(p, c)]
    if changed:
        print(f"bp table ({len(t)} names) regenerated: {', '.join(changed)}")
    else:
        print(f"bp table ({len(t)} names) already in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
