#!/usr/bin/env bash
# sovereignty_report.sh — the MEASURED sovereignty receipt: real token payload + real native readiness.
#
# Carrier only. It gathers MEASURED numbers from two live feeds and presents them; the decision logic is
# Form (sovereignty-receipt.fk + attention-signal.fk, four-way proven). Where to pay attention falls out
# of the measured per-lane gap — a high-volume, low-native-score lane is where the next training breath goes.
#   feed 1 — the active Claude Code session transcript -> real token payload (in/out)
#   feed 2 — `form-cli stats` -> real native readiness (held-out scores, local-suffice rate, sample count)
set -u
ROOT="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 0

echo "⟐ SOVEREIGNTY RECEIPT (measured) — $(cd "$ROOT" && git rev-parse --short HEAD 2>/dev/null)"
echo "  oracle: Anthropic · model: claude-opus-4-8 (the generating mind today)"
echo

# ── feed 1: payload (real tokens from the active session transcript, if reachable) ──
TX="$(find "$HOME/.claude/projects" -name '*.jsonl' -path '*Coherence-Network*' 2>/dev/null \
      | xargs ls -t 2>/dev/null | head -1)"
if [ -n "${TX:-}" ] && [ -f "$TX" ]; then
  IN=$(grep -oE '"input_tokens":[0-9]+'  "$TX" 2>/dev/null | grep -oE '[0-9]+' | awk '{s+=$1} END{print s+0}')
  OUT=$(grep -oE '"output_tokens":[0-9]+' "$TX" 2>/dev/null | grep -oE '[0-9]+' | awk '{s+=$1} END{print s+0}')
  echo "  payload (measured, this session): ~${IN} in / ${OUT} out tokens — 100% generated by the rented oracle"
else
  echo "  payload: session transcript not reachable from here (estimate only — name the uncertainty)"
fi
echo "  native this session: VERIFICATION (four-way proofs) + LOOKUP — not generation."
echo

# ── feed 2: native readiness (the real measured held-out scores) ──
echo "  native readiness (form-cli stats — measured held-out, the contender vs the corpus):"
if [ -x "$ROOT/bin/form-cli" ]; then
  "$ROOT/bin/form-cli" stats 2>/dev/null \
    | sed -n '/── learning ──/,/── tool → native/p;/── tool → native/,/── local oracle/p' \
    | grep -vE '^\s*── (tool → native)' | sed 's/^/    /'
else
  echo "    (form-cli not built — run scripts/ensure_form_cli_kernel.sh)"
fi
echo

# ── feed 3: native-thought routing — the tally is Form (host-read + count in native-thought-receipt.fk) ──
NTR="${NATIVE_THOUGHT_RECEIPTS:-$HOME/.coherence-network/native-thought-receipts.jsonl}"
GO="$ROOT/form/form-kernel-go/bin-go"; STD="$ROOT/form/form-stdlib"
if [ -f "$NTR" ] && [ -x "$GO" ]; then
  drv="$(mktemp --suffix=.fk)"; printf '(do (print (ntr-tally "%s")))\n' "$NTR" > "$drv"
  read -r N HIT ESC <<<"$("$GO" "$STD/sovereignty-receipt.fk" "$STD/native-thought-receipt.fk" "$drv" 2>/dev/null | grep -E '^[0-9]+ [0-9]+ [0-9]+$' | head -1)"
  rm -f "$drv"
  if [ "${N:-0}" -gt 0 ] 2>/dev/null; then
    PCT=$(( 100 * HIT / N ))
    echo "  native-thought routing (Form tally over the receipt ledger): ${N} thoughts routed — ${HIT} came home (body-hit), ${ESC} rented (escalated) → ${PCT}% sovereign this body"
    echo "    each escalated row is a free training sample (borrowed-oracle-dividend.form); watch the % rise."
  else
    echo "  native-thought routing: ledger present, no decisions recorded yet."
  fi
else
  echo "  native-thought routing: no ledger yet — the door records via scripts/native_thought_receipt.sh (logic in native-thought-receipt.fk)."
fi
echo

# ── where to pay attention (attention-signal.fk tiering over the measured per-lane scores) ──
echo "  → attention (attention-signal.fk, four-way): rank lanes by measured gap × volume."
echo "    ATTEND  — high volume, far from native: Read/Edit/Write tool-prediction (~65%)."
echo "    LAST MILE — high volume, near-native: Bash (97%), StructuredOutput (99%)."
echo "    GROW    — the corpus itself: route more asks through 'form-cli ask' so the held-out set grows."
echo
echo "  the honest floor: an agentic response is generated ~100% by the rented mind; this report is the"
echo "  signal for which lane to bring home next. Teaching: docs/coherence-substrate/sovereignty-receipt.form"
exit 0
