#!/usr/bin/env bash
# validate_form_cli_local_receipts.sh — local receipts for the form-cli ask lane.
#
# This proves the honest floor:
#   - `form-cli ask` is served by the native fkwu grounded-RAG lane.
#   - a local ask-staged miss binds a decoded grounded answer to the fkwu+Metal
#     model-cell witness.
#   - a full-width GGUF token-embedding logit row is generated by fkwu/Form.
#   - full real Llama GGUF token generation is still not claimed.
#   - the Metal witnesses and Form proof bands that back those pieces still pass.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
QUERY="${1:-substrate}"
FAIL=0

ok() { printf "  ✓  %s\n" "$1"; }
gap() { printf "  ✗  %s\n" "$1"; FAIL=1; }
note() { printf "     %s\n" "$1"; }

run_receipt() {
    label="$1"; shift
    out="$("$@" 2>&1)"
    rc=$?
    if [[ "$rc" -eq 0 ]]; then
        ok "$label"
        printf '%s\n' "$out" | sed -n '1,6p' | sed 's/^/     /'
    else
        gap "$label"
        printf '%s\n' "$out" | sed -n '1,20p' | sed 's/^/     /'
    fi
}

echo "── form-cli local receipts ──"

ask_out="$("$ROOT/bin/form-cli" ask "$QUERY" 2>&1)"
if grep -q '^grounded:' <<<"$ask_out" &&
   grep -q '^local-lane:fkwu-rag-grounded' <<<"$ask_out" &&
   grep -q '^synthesis-lane:fkwu-rag-grounded' <<<"$ask_out"; then
    ok "native fkwu ask grounded locally for query: $QUERY"
    printf '%s\n' "$ask_out" | sed 's/^/     /'
else
    gap "native fkwu ask did not produce the expected grounded local receipt"
    printf '%s\n' "$ask_out" | sed 's/^/     /'
fi

model_probe="local receipt grounded inference probe $(date -u +%Y%m%dT%H%M%SZ)"
"$ROOT/bin/form-cli" ask "$model_probe" >/dev/null 2>&1

synth_out="$("$ROOT/bin/form-cli" synthesis-status 2>&1)"
if { grep -q '^synthesis-lane:fkwu-metal-answer-bound' <<<"$synth_out" ||
     grep -q '^synthesis-lane:grounded-fkwu-model-answer' <<<"$synth_out"; } &&
   grep -q '^available:gguf-locate,gguf-model-cell,gguf-tensor-slice-math,gguf-tensor-set-cell,gguf-semantic-token-generation,gguf-fullwidth-logit-generation,weight-load,block-join,real-gguf-tensor-math-four-way,metal-matvec,metal-model-cell,metal-decode-step,tokenizer-carrier-four-way,llama3-pretokenizer-four-way,real-gguf-tensor-map,metal-weight-bytes-runtime,autoregressive-loop-four-way,ask-staged-model-call-witness,decoded-prose-answer-binding' <<<"$synth_out" &&
   grep -q '^observed:tokenizer-carrier,full-gguf-weight-map,named-real-gguf-tensor-math,full-gguf-named-tensor-slice-math,full-gguf-required-tensor-set-materialization,real-gguf-tokenizer-token-decode,semantic-token-generation,full-width-model-logit-generation,metal-weight-bytes-runtime,autoregressive-loop,ask-staged-model-call,decoded-prose-answer-binding' <<<"$synth_out" &&
   grep -q '^missing:full-real-llama-gguf-token-generation' <<<"$synth_out" &&
   grep -q '^prose-generation:decoded-grounded-answer' <<<"$synth_out"; then
    ok "synthesis lane receipt binds grounded decoded answer and names full real generation"
    printf '%s\n' "$synth_out" | sed 's/^/     /'
else
    gap "synthesis lane receipt is missing or ambiguous"
    printf '%s\n' "$synth_out" | sed 's/^/     /'
fi

run_receipt "form-cli native dispatch band" \
    bash -lc "cd '$ROOT/form' && ./validate.sh form-stdlib/core.fk form-stdlib/text-tokenize.fk form-stdlib/rag-embed.fk form-stdlib/rag-index-codec.fk form-stdlib/rag-retrieve.fk form-stdlib/rag-ask.fk form-stdlib/form-cli-ask.fk form-stdlib/line-grammar.fk form-stdlib/voice-traits.fk form-stdlib/nearest-shape.fk form-stdlib/co-learning.fk form-stdlib/co-learning-stream.fk form-stdlib/mesh-dispatch.fk form-stdlib/surprise-salience.fk form-stdlib/host-sense-organ.fk form-stdlib/speech-organ.fk form-stdlib/native-host-instance.fk form-stdlib/resource-port.fk form-stdlib/bml-native-interface-package-import.fk form-stdlib/hati-os-targets.fk form-stdlib/form-native-resource-interfaces.fk form-stdlib/form-fs.fk form-stdlib/storage-port.fk form-stdlib/host-kernel-carrier.fk form-stdlib/fnri-standin.fk form-stdlib/fnri-receipt.fk form-stdlib/current-branch-landing.fk form-stdlib/form-cli.fk form-stdlib/tests/form-cli-band.fk"
run_receipt "GGUF weight-load/block-join band" \
    bash -lc "cd '$ROOT/form' && ./validate.sh form-stdlib/core.fk form-stdlib/format-arith.fk form-stdlib/f16-decode.fk form-stdlib/gguf-read.fk form-stdlib/q6k-dequant.fk form-stdlib/weight-load.fk form-stdlib/transformer-block.fk form-stdlib/llama-block.fk form-stdlib/block-join.fk form-stdlib/tests/block-join-band.fk"
run_receipt "named real GGUF tensor math band" \
    bash -lc "cd '$ROOT/form' && ./validate.sh form-stdlib/core.fk form-stdlib/format-arith.fk form-stdlib/f16-decode.fk form-stdlib/gguf-read.fk form-stdlib/q6k-dequant.fk form-stdlib/weight-load.fk form-stdlib/transformer-block.fk form-stdlib/block-join.fk form-stdlib/real-gguf-tensor-math.fk form-stdlib/tests/real-gguf-tensor-math-band.fk"
run_receipt "cached generation semantics band" \
    bash -lc "cd '$ROOT/form' && ./validate.sh form-stdlib/trig.fk form-stdlib/transformer-numerics.fk form-stdlib/transformer-block.fk form-stdlib/transformer-mh.fk form-stdlib/transformer-decoder.fk form-stdlib/transformer-generate.fk form-stdlib/transformer-generate-cached.fk form-stdlib/tests/transformer-generate-cached-band.fk"
run_receipt "Metal emitter band" \
    bash -lc "cd '$ROOT/form' && ./validate.sh form-stdlib/jit-tensor-emit.fk form-stdlib/tests/metal-emit-band.fk"
run_receipt "form-cli model-lane gap receipt" \
    "$ROOT/scripts/validate_form_cli_model_lane_gap_receipts.sh" "$ROOT/.cache/body-test-receipts/current-model-lane-gap-receipt.json"
run_receipt "fkwu form-cli GGUF model-cell receipt" \
    "$ROOT/scripts/fkwu_form_cli_gguf_model_cell_receipt.sh" "$ROOT/.cache/body-test-receipts/current-gguf-model-cell-receipt.json"
run_receipt "fkwu form-cli full GGUF tensor-slice math receipt" \
    "$ROOT/scripts/fkwu_form_cli_full_gguf_tensor_slice_math_receipt.sh" "$ROOT/.cache/body-test-receipts/current-full-gguf-tensor-slice-math-receipt.json"
run_receipt "fkwu form-cli full GGUF tensor-set materialization receipt" \
    "$ROOT/scripts/fkwu_form_cli_full_gguf_tensor_set_materialization_receipt.sh" "$ROOT/.cache/body-test-receipts/current-full-gguf-tensor-set-materialization-receipt.json"
run_receipt "fkwu form-cli real GGUF semantic-token generation receipt" \
    "$ROOT/scripts/fkwu_form_cli_gguf_semantic_token_generation_receipt.sh" "$ROOT/.cache/body-test-receipts/current-gguf-semantic-token-generation-receipt.json"
run_receipt "fkwu form-cli full-width GGUF model-logit generation receipt" \
    "$ROOT/scripts/fkwu_form_cli_gguf_fullwidth_logits_receipt.sh" "$ROOT/.cache/body-test-receipts/current-gguf-fullwidth-logits-receipt.json"

if [[ "$(uname -s)" == "Darwin" ]] && command -v swiftc >/dev/null 2>&1; then
    run_receipt "Metal matvec witness" "$ROOT/scripts/metal_matvec_audit.sh" 16 16 1
    run_receipt "Metal llama decode-step witness" "$ROOT/scripts/metal_llama_block_decode_audit.sh"
    run_receipt "fkwu form-cli Metal model-cell receipt" \
        "$ROOT/scripts/fkwu_form_cli_metal_model_cell_receipt.sh" "$ROOT/.cache/body-test-receipts/current-model-cell-receipt.json"
else
    note "Metal witnesses skipped: Darwin + swiftc unavailable on this host"
fi

echo "── verdict ──"
if [[ "$FAIL" -eq 0 ]]; then
    echo "  PASS: local grounded ask, semantic-token generation, full-width logit generation, and grounded decoded-answer receipts are honest."
    echo "  The full real Llama GGUF token generator is still not claimed."
else
    echo "  FAIL: one or more local receipts did not hold."
fi
exit "$FAIL"
