"""Coherence-substrate — content-addressed numeric lattice for the Network.

A structural substrate for the body's tissue (ideas, specs, concepts,
memories, presences, lineages, tasks, witnesses). The kernel is universal;
the category vocabulary is Network-specific.

Public API:
    from app.services.substrate import (
        NodeID, Recipe, NamedCell,
        make_cell, lookup_cell, find_equivalent_cells,
        intern_node, lattice_stats,
        ingest_memory_file,
    )

See:
    docs/field/urs/artifacts/nums-go-2023/network-substrate-design.md
    docs/field/urs/artifacts/nums-go-2023/study-notes.md
"""
from __future__ import annotations

from app.services.substrate.kernel import (
    DOMAIN_BLUEPRINT,
    DOMAIN_RECIPE,
    CellView,
    NamedCell,
    NodeID,
    PathAnnotation,
    Recipe,
    annotate_path,
    find_cells_compatible_with,
    find_downstream_cells,
    find_equivalent_cells,
    get_level,
    intern_node,
    lattice_stats,
    lookup_cell,
    lookup_node,
    make_cell,
    make_composite_blueprint,
    make_trivial_blueprint,
    serialize_tree,
    view_cell_through_blueprint,
    vocabulary_histogram,
)
from app.services.substrate.resonance import (
    BID_geometric_form,
    BID_harmonic,
    BID_polarity,
    BID_spectrum,
    BID_topology,
    DOMAIN_GEOMETRIC_FORM,
    DOMAIN_HARMONIC,
    DOMAIN_POLARITY,
    DOMAIN_SPECTRUM,
    DOMAIN_TOPOLOGY,
    author_geometry_signature,
    bridges_edge,
    bridges_symmetric,
    carries_ratio_edge,
    commutative_edge,
    cell_resonance_signature,
    coherence_distance,
    coherence_score,
    embeds_in_edge,
    find_cells_harmonic_at,
    find_cells_shaping,
    find_cells_via_resonance,
    geometric_form_cell,
    harmonic_at_edge,
    harmonic_cell,
    hz_cell,
    near_edge,
    near_symmetric,
    polar_to_edge,
    polar_to_symmetric,
    polarity_cell,
    shapes_edge,
    topology_cell,
)
from app.services.substrate.modality_shapes import (
    CANONICAL_SHAPES,
    DOMAIN_RECIPE_SHAPE,
    canonical_shape_names,
    intern_all_canonical_shapes,
    intern_canonical_shape,
    shape_signature_blueprint,
)
from app.services.substrate.markdown_frontend import (
    BID_concept,
    BID_idea,
    BID_guide,
    BID_kb_page,
    BID_language_view,
    BID_lineage,
    BID_memory,
    BID_object,
    BID_path,
    BID_presence,
    BID_resource,
    BID_slug,
    BID_spec,
    BID_artifact,
    BID_string,
    BID_task,
    BID_transmission,
    BID_witness,
    BID_word,
    artifact_kind_hz,
    frontmatter_to_blueprint,
    ingest_concept_file,
    ingest_git_artifact,
    ingest_guide_file,
    ingest_idea_file,
    ingest_kb_page_file,
    ingest_language_view_file,
    ingest_lineage_file,
    ingest_markdown_text,
    ingest_memory_file,
    ingest_presence_file,
    ingest_resource_file,
    ingest_spec_file,
    ingest_task,
    ingest_word_cell,
    lemma_pos_key,
    tokenize_words,
    ingest_transmission_file,
    ingest_witness_event,
    parse_markdown,
    parse_markdown_file,
)

__all__ = [
    # kernel
    "CellView",
    "DOMAIN_BLUEPRINT",
    "DOMAIN_RECIPE",
    "NamedCell",
    "NodeID",
    "PathAnnotation",
    "Recipe",
    "annotate_path",
    "find_cells_compatible_with",
    "find_downstream_cells",
    "find_equivalent_cells",
    "get_level",
    "intern_node",
    "lattice_stats",
    "lookup_cell",
    "lookup_node",
    "make_cell",
    "make_composite_blueprint",
    "make_trivial_blueprint",
    "serialize_tree",
    "view_cell_through_blueprint",
    "vocabulary_histogram",
    # category constructors
    "BID_concept",
    "BID_guide",
    "BID_idea",
    "BID_kb_page",
    "BID_language_view",
    "BID_lineage",
    "BID_memory",
    "BID_object",
    "BID_path",
    "BID_presence",
    "BID_resource",
    "BID_artifact",
    "BID_slug",
    "BID_spec",
    "BID_string",
    "BID_task",
    "BID_transmission",
    "BID_witness",
    "BID_word",
    # frontends
    "artifact_kind_hz",
    "frontmatter_to_blueprint",
    "ingest_concept_file",
    "ingest_git_artifact",
    "ingest_guide_file",
    "ingest_idea_file",
    "ingest_kb_page_file",
    "ingest_language_view_file",
    "ingest_lineage_file",
    "ingest_markdown_text",
    "ingest_memory_file",
    "ingest_presence_file",
    "ingest_resource_file",
    "ingest_spec_file",
    "ingest_task",
    "ingest_word_cell",
    "lemma_pos_key",
    "tokenize_words",
    "ingest_transmission_file",
    "ingest_witness_event",
    "parse_markdown",
    "parse_markdown_file",
    # Resonance — dimensional vocabulary + edge authoring
    "BID_geometric_form",
    "BID_harmonic",
    "BID_polarity",
    "BID_spectrum",
    "BID_topology",
    "DOMAIN_GEOMETRIC_FORM",
    "DOMAIN_HARMONIC",
    "DOMAIN_POLARITY",
    "DOMAIN_SPECTRUM",
    "DOMAIN_TOPOLOGY",
    "author_geometry_signature",
    "bridges_edge",
    "bridges_symmetric",
    "carries_ratio_edge",
    "commutative_edge",
    "embeds_in_edge",
    "cell_resonance_signature",
    "coherence_distance",
    "coherence_score",
    "find_cells_harmonic_at",
    "find_cells_shaping",
    "find_cells_via_resonance",
    "geometric_form_cell",
    "harmonic_at_edge",
    "harmonic_cell",
    "hz_cell",
    "near_edge",
    "near_symmetric",
    "polar_to_edge",
    "polar_to_symmetric",
    "polarity_cell",
    "shapes_edge",
    "topology_cell",
    # Modality shapes — cross-modal canonical recipe shapes
    "CANONICAL_SHAPES",
    "DOMAIN_RECIPE_SHAPE",
    "canonical_shape_names",
    "intern_all_canonical_shapes",
    "intern_canonical_shape",
    "shape_signature_blueprint",
]
