"""Coherence-substrate — content-addressed numeric lattice for the Network.

A structural substrate for the body's tissue (ideas, specs, concepts,
memories, presences, lineages, tasks, witnesses). The kernel is universal;
the category vocabulary is Network-specific.

Public API:
    from app.services.substrate import (
        NodeID, Recipe, NamedCell,
        make_cell, lookup_cell, find_equivalent_cells,
        intern_node, lattice_stats,
        ingest_memory_file,
    )

See:
    docs/field/urs/artifacts/nums-go-2023/network-substrate-design.md
    docs/field/urs/artifacts/nums-go-2023/study-notes.md
"""
from __future__ import annotations

from app.services.substrate.kernel import (
    DOMAIN_BLUEPRINT,
    DOMAIN_RECIPE,
    CellView,
    NamedCell,
    NodeID,
    PathAnnotation,
    Recipe,
    annotate_path,
    find_cells_compatible_with,
    find_equivalent_cells,
    get_level,
    intern_node,
    lattice_stats,
    lookup_cell,
    lookup_node,
    make_cell,
    make_composite_blueprint,
    make_trivial_blueprint,
    serialize_tree,
    view_cell_through_blueprint,
    vocabulary_histogram,
)
from app.services.substrate.form import (
    FormResult,
    evaluate as form_evaluate,
    evaluate_text as form_evaluate_text,
    parse as form_parse,
    serialize_cell as form_serialize_cell,
    serialize_node_id as form_serialize_node_id,
)
from app.services.substrate.form_stream import (
    parse_and_emit as form_stream_emit,
)
from app.services.substrate.form_runtime import (
    Frame as FormFrame,
    execute as form_execute,
    form_execute_text,
)
from app.services.substrate.grammar import (
    BID_grammar,
    FormRule,
    list_form_rules,
    lookup_form_rule,
    register_form_rule,
)
from app.services.substrate.form_builders import (
    Build,
    CaptureRef,
    Const,
    MapBuild,
    execute_template,
    make_builder_from_template,
    recipe_to_template,
    template_to_recipe,
)
from app.services.substrate.form_eval import (
    list_eval_mappings,
    lookup_eval_category,
    register_eval,
    reset_eval_registry,
)
from app.services.substrate.form_speculation import (
    FailSignal,
    SpeculationContext,
    SpeculationFrame,
    SpeculationResult,
    StopSignal,
    choice,
    speculate,
)
from app.services.substrate.form_operators import (
    OperatorRule,
    list_operators,
    lookup_binary_operator,
    lookup_operator,
    lookup_unary_prefix_operator,
    parse_with_precedence,
    register_operator,
    reset_operator_registry,
    unregister_operator,
)
from app.services.substrate.self_host import (
    bootstrap_full_self_host,
    bootstrap_self_host,
    bootstrap_self_host_operators,
    list_bootstrap_self_host_keywords,
)
from app.services.substrate.form_rules import (
    Capture,
    IdentCapture,
    Literal,
    Opt,
    RepeatedCapture,
    Sequence,
    list_builders,
    list_registered_keywords,
    load_all_keywords_from_substrate,
    load_keyword_from_substrate,
    lookup_builder,
    lookup_form_keyword,
    pattern_to_recipe,
    recipe_to_pattern,
    register_builder,
    register_form_keyword,
    unregister_form_keyword,
)
from app.services.substrate.recipe_eval import (
    Environment as RecipeEnvironment,
    ExecutionContext,
    RaiseSignal,
    eval_recipe,
    eval_text as recipe_eval_text,
)
# Note: FailSignal/StopSignal are NOT re-exported from recipe_eval to avoid
# collision with the parser-level versions already exported by form_speculation.
# Import them directly from recipe_eval when needed at the runtime layer:
#     from app.services.substrate.recipe_eval import FailSignal, StopSignal
from app.services.substrate.resonance import (
    BID_geometric_form,
    BID_harmonic,
    BID_polarity,
    BID_spectrum,
    BID_topology,
    DOMAIN_GEOMETRIC_FORM,
    DOMAIN_HARMONIC,
    DOMAIN_POLARITY,
    DOMAIN_SPECTRUM,
    DOMAIN_TOPOLOGY,
    author_geometry_signature,
    bridges_edge,
    bridges_symmetric,
    carries_ratio_edge,
    commutative_edge,
    embeds_in_edge,
    find_cells_harmonic_at,
    find_cells_shaping,
    find_cells_via_resonance,
    geometric_form_cell,
    harmonic_at_edge,
    harmonic_cell,
    hz_cell,
    near_edge,
    near_symmetric,
    polar_to_edge,
    polar_to_symmetric,
    polarity_cell,
    shapes_edge,
    topology_cell,
)
from app.services.substrate.markdown_frontend import (
    BID_concept,
    BID_idea,
    BID_guide,
    BID_kb_page,
    BID_language_view,
    BID_lineage,
    BID_memory,
    BID_object,
    BID_path,
    BID_presence,
    BID_resource,
    BID_slug,
    BID_spec,
    BID_string,
    BID_task,
    BID_transmission,
    BID_witness,
    frontmatter_to_blueprint,
    ingest_concept_file,
    ingest_guide_file,
    ingest_idea_file,
    ingest_kb_page_file,
    ingest_language_view_file,
    ingest_lineage_file,
    ingest_markdown_text,
    ingest_memory_file,
    ingest_presence_file,
    ingest_resource_file,
    ingest_spec_file,
    ingest_task,
    ingest_transmission_file,
    ingest_witness_event,
    parse_markdown,
    parse_markdown_file,
)

__all__ = [
    # kernel
    "CellView",
    "DOMAIN_BLUEPRINT",
    "DOMAIN_RECIPE",
    "NamedCell",
    "NodeID",
    "PathAnnotation",
    "Recipe",
    "annotate_path",
    "find_cells_compatible_with",
    "find_equivalent_cells",
    "get_level",
    "intern_node",
    "lattice_stats",
    "lookup_cell",
    "lookup_node",
    "make_cell",
    "make_composite_blueprint",
    "make_trivial_blueprint",
    "serialize_tree",
    "view_cell_through_blueprint",
    "vocabulary_histogram",
    # category constructors
    "BID_concept",
    "BID_guide",
    "BID_idea",
    "BID_kb_page",
    "BID_language_view",
    "BID_lineage",
    "BID_memory",
    "BID_object",
    "BID_path",
    "BID_presence",
    "BID_resource",
    "BID_slug",
    "BID_spec",
    "BID_string",
    "BID_task",
    "BID_transmission",
    "BID_witness",
    # frontends
    "frontmatter_to_blueprint",
    "ingest_concept_file",
    "ingest_guide_file",
    "ingest_idea_file",
    "ingest_kb_page_file",
    "ingest_language_view_file",
    "ingest_lineage_file",
    "ingest_markdown_text",
    "ingest_memory_file",
    "ingest_presence_file",
    "ingest_resource_file",
    "ingest_spec_file",
    "ingest_task",
    "ingest_transmission_file",
    "ingest_witness_event",
    "parse_markdown",
    "parse_markdown_file",
    # Form
    "FormResult",
    "form_evaluate",
    "form_evaluate_text",
    "form_execute",
    "form_execute_text",
    "FormFrame",
    "form_parse",
    "form_serialize_cell",
    "form_serialize_node_id",
    "form_stream_emit",
    # Grammar — substrate-resident parse rules (BMF-shaped seed)
    "BID_grammar",
    "FormRule",
    "list_form_rules",
    "lookup_form_rule",
    "register_form_rule",
    # Rule-driven extension — runtime keyword registration
    "Capture",
    "IdentCapture",
    "Literal",
    "Opt",
    "RepeatedCapture",
    "Sequence",
    "list_builders",
    "list_registered_keywords",
    "load_all_keywords_from_substrate",
    "load_keyword_from_substrate",
    "lookup_builder",
    "lookup_form_keyword",
    "pattern_to_recipe",
    "recipe_to_pattern",
    "register_builder",
    "register_form_keyword",
    "unregister_form_keyword",
    # Substrate-resident builders (Build/CaptureRef/Const template DSL)
    "Build",
    "CaptureRef",
    "Const",
    "MapBuild",
    "execute_template",
    "make_builder_from_template",
    "recipe_to_template",
    "template_to_recipe",
    # Self-hosting
    "bootstrap_self_host",
    "bootstrap_self_host_operators",
    "bootstrap_full_self_host",
    "list_bootstrap_self_host_keywords",
    # Operator registry
    "OperatorRule",
    "list_operators",
    "lookup_binary_operator",
    "lookup_operator",
    "lookup_unary_prefix_operator",
    "parse_with_precedence",
    "register_operator",
    "reset_operator_registry",
    "unregister_operator",
    # Eval-category registry (data-driven evaluator)
    "list_eval_mappings",
    "lookup_eval_category",
    "register_eval",
    "reset_eval_registry",
    # Parser-level speculation (backtracking-without-sediment)
    "FailSignal",
    "SpeculationContext",
    "SpeculationFrame",
    "SpeculationResult",
    "StopSignal",
    "choice",
    "speculate",
    # Resonance — dimensional vocabulary + edge authoring
    "BID_geometric_form",
    "BID_harmonic",
    "BID_polarity",
    "BID_spectrum",
    "BID_topology",
    "DOMAIN_GEOMETRIC_FORM",
    "DOMAIN_HARMONIC",
    "DOMAIN_POLARITY",
    "DOMAIN_SPECTRUM",
    "DOMAIN_TOPOLOGY",
    "author_geometry_signature",
    "bridges_edge",
    "bridges_symmetric",
    "carries_ratio_edge",
    "commutative_edge",
    "embeds_in_edge",
    # Recipe-execution engine (runtime semantics for form-layer constructs)
    "ExecutionContext",
    "RaiseSignal",
    "RecipeEnvironment",
    "eval_recipe",
    "recipe_eval_text",
    "find_cells_harmonic_at",
    "find_cells_shaping",
    "find_cells_via_resonance",
    "geometric_form_cell",
    "harmonic_at_edge",
    "harmonic_cell",
    "hz_cell",
    "near_edge",
    "near_symmetric",
    "polar_to_edge",
    "polar_to_symmetric",
    "polarity_cell",
    "shapes_edge",
    "topology_cell",
]
