// ════════════════════════════════════════════════════════════════════
// MASCHINELL ÜBERSETZT · machine-translated from en.tsx
// Generated by scripts/generate_curated_translations.py via libretranslate.
// JSX structure preserved via placeholder-tag pre/post processing.
// Refinement welcome — replace any line with author-curated prose at
// any time; the locale-router will pick this file up automatically.
// To regenerate: python3 scripts/generate_curated_translations.py \
//                  --slug schindler-hc11-protocol --target-lang id
// ════════════════════════════════════════════════════════════════════
import Link from "next/link";
import type { PersonProfileContent } from "@/components/people/PersonProfileTemplate";

const content: PersonProfileContent = {
  metadata: {title: "Schindler HC11 - ISO / OSI 7- lapis stack dalam perangkat keras (usia 18)",description: "Pada usia 18, ketika di Schindler di Swiss, dirancang perangkat keras dan menulis firmware untuk sebuah ISO / OSI 7-layer protokol stack pada Motorola HC11 microcontroller - beberapa UART jaringan menjadi satu papan, EPROM dan PAL programmware, semua firmware dalam C, dan sebuah gustom debugger karena tidak ada off-the- rak ada untuk bring- up. Di mana Urs pertama kali belajar C - lima tahun setelah Komodor 64 MIDI bekerja di mana BASIC dan 6510 perakitan sudah akrab.",
  },breadcrumbName: "Schindler HC11 - 7- layer dalam perangkat keras",
  hero: {
    background:
      "linear-gradient(135deg, hsl(220 30% 8%), hsl(0 35% 14%) 50%, hsl(20 30% 16%))",
    overlayClass:
      "absolute inset-0 bg-gradient-to-t from-background via-background/85 to-background/30",eyebrow: "Pekerjaan",
    eyebrowClass: "text-[hsl(var(--chart-2))]",name: "Schindler HC11 - 7- layer protokol dalam perangkat keras",
    welcome: (
      <p>
        Age 18, in Switzerland. Designed the hardware{" "}
        <em>and</em> wrote the firmware for an{" "}
        <strong>ISO/OSI 7-layer protocol stack</strong> on a{" "}
        <strong>Motorola HC11</strong> microcontroller. Multiple UARTs
        networked into a working bus, EPROM and PAL programmable
        blocks defining the discrete logic, every layer of firmware
        written in <strong>C</strong>. No off-the-shelf debugger
        existed for the bring-up — built one. Five years after the{" "}
        <Link href="/people/c64-midi-interface" className="text-primary hover:underline">
          Commodore 64 MIDI work
        </Link>
        {" "}made BASIC and 6510 assembly familiar territory, this is
        where this body picked up C — at the substrate where every
        byte mattered and no instruction came pre-debugged.
      </p>
    ),
  },
  facts: [
    {label: "Era",value: "Schindler" },
    {label: "Perangkat Keras",
      value: (
        <>
          <Link href="https://en.wikipedia.org/wiki/Motorola_68HC11" target="_blank" rel="noopener noreferrer" className="hover:text-primary">Motorola 68HC11</Link>
          {" "}microcontroller · multiple UARTs · EPROM (program storage) · PAL (programmable array logic, the "discrete glue logic" of the era) · custom-designed board
        </>
      ),
    },
    {label: "Firmware",value: "C - full ISO / OSI 7- layer protokol stack dari fisik / data- link up melalui aplikasi - berjalan pada logam telanjang, tidak ada OS"
    },
    {label: "Tooling",value: "Debugger gubahan yang ditulis dari scratch - bring-up lingkungan dengan tidak ada off- the- rak pilihan"
    },
    {label: "Penandaan",
      value: (
        <>
          Learned C in the hardest place to learn it: an embedded
          target with EPROM cycles, no OS, and a debugger that didn't
          exist until written. This conviction —{" "}
          <em>build the tool you need, all the way down</em> — threads
          through every later iteration.
        </>
      ),
    },
    {label: "Garis Keturunan kedepan",
      value: (
        <>
          The same "every layer addressable" posture re-emerges in{" "}
          <Link href="/people/bml-language" className="hover:text-primary">BML (2000)</Link>
          {" "}as grammar-in-grammar, in{" "}
          <Link href="/people/quark-virtual-dom" className="hover:text-primary">Quark Virtual DOM (2000-2005)</Link>
          {" "}as application-as-DOM-tree, and in{" "}
          <Link href="/people/coherence-network" className="hover:text-primary">Coherence-Network</Link>
          {" "}as everything-is-a-node.
        </>
      ),
    },
  ],
  noteFromBody: {eyebrow: "Mengapa pekerjaan ini penting",
    body: (
      <p>
        Most engineers learn C through tutorials. This body learned C
        by sitting in front of a board it had drawn and a chip it had
        soldered in, with EPROMs that took minutes to erase under
        ultraviolet and a debugger it had to write before it could
        even watch the firmware run. That experience set the
        permission level for every later piece of work: <em>if the
        tool you need doesn't exist, you build it</em> — language,
        grammar, parser, VM, virtual DOM, undo engine, harness,
        network. All of it descends from this board.
      </p>
    ),
  },
  articles: [
    {
      kind: "narrative",heading: "Apa yang ada di papan",
      body: (
        <>
          <p>
            The HC11 era — late 1980s into the early 1990s — was the
            golden window of "do the whole stack yourself" embedded
            engineering. The chip itself sat on a custom-designed
            board with the discrete-logic glue routed through{" "}
            <strong>PAL</strong> (Programmable Array Logic) chips —
            small ICs you'd burn with your own truth tables, the
            ancestor of the FPGA. The HC11 had on-board RAM and a
            single hardware UART; the board added more UART devices
            on the bus so several physical lines could feed in at
            once and let the protocol stack run as a small network
            from a single processor.
          </p>
          <figure className="my-6 rounded-xl border border-border/40 bg-card/30 p-5">
            <svg viewBox="0 0 720 300" className="w-full h-auto" role="img" aria-labelledby="hc11-board-title">
              <title id="hc11-board-title">Schindler HC11 board topology</title>
              <g fontFamily="ui-sans-serif,system-ui" fontSize="12">
                {/* HC11 in center */}
                <rect x="290" y="120" width="140" height="80" rx="8" fill="hsl(220 30% 18%)" stroke="hsl(40 80% 60%)" strokeWidth="2" />
                <text x="360" y="148" textAnchor="middle" fill="hsl(40 90% 85%)" fontSize="14">Motorola HC11</text>
                <text x="360" y="166" textAnchor="middle" fill="hsl(40 60% 75%)" fontSize="10">8-bit MCU · on-chip RAM</text>
                <text x="360" y="182" textAnchor="middle" fill="hsl(40 60% 75%)" fontSize="10">single HW UART · timers · ports</text>

                {/* EPROM */}
                <rect x="60" y="40" width="140" height="60" rx="8" fill="hsl(220 25% 16%)" stroke="hsl(195 60% 60%)" />
                <text x="130" y="64" textAnchor="middle" fill="hsl(195 80% 82%)" fontSize="13">EPROM</text>
                <text x="130" y="82" textAnchor="middle" fill="hsl(195 50% 70%)" fontSize="10">UV-erasable program storage</text>
                <line x1="200" y1="80" x2="290" y2="135" stroke="hsl(195 50% 60%)" strokeWidth="1.2" />

                {/* PAL */}
                <rect x="60" y="220" width="140" height="60" rx="8" fill="hsl(220 25% 16%)" stroke="hsl(280 55% 65%)" />
                <text x="130" y="244" textAnchor="middle" fill="hsl(280 80% 82%)" fontSize="13">PAL</text>
                <text x="130" y="262" textAnchor="middle" fill="hsl(280 55% 75%)" fontSize="10">programmable glue logic</text>
                <line x1="200" y1="240" x2="290" y2="190" stroke="hsl(280 50% 65%)" strokeWidth="1.2" />

                {/* UARTs on right */}
                {[
                  ["UART 1", 60],
                  ["UART 2", 110],
                  ["UART 3", 160],
                  ["UART 4", 210],
                ].map(([label, y], i) => {
                  const yn = Number(y);
                  return (
                    <g key={i}>
                      <rect x="520" y={yn} width="140" height="36" rx="6" fill="hsl(220 25% 16%)" stroke="hsl(140 55% 60%)" />
                      <text x="590" y={yn + 22} textAnchor="middle" fill="hsl(140 80% 82%)" fontSize="11">{String(label)}</text>
                      <line x1="430" y1="160" x2="520" y2={yn + 18} stroke="hsl(140 50% 60%)" strokeWidth="1.2" />
                    </g>
                  );
                })}

                <text x="590" y="270" textAnchor="middle" fill="hsl(140 50% 75%)" fontSize="10" fontStyle="italic">
                  multiple physical lines → one bus → one processor
                </text>
              </g>
            </svg>
            <figcaption className="text-xs text-muted-foreground mt-3 text-center">
              The custom board topology. HC11 in the centre with EPROM
              feeding instructions in, PAL providing the discrete glue
              logic, and multiple UARTs hanging off the bus to make
              one processor look like a small network.
            </figcaption>
          </figure>
          <p>
            "Designed all by me" in the user's own framing means the
            schematic, the parts selection, the trace routing, the
            PAL truth-tables, and the timing analysis. The kind of
            engineering where a single soldering mistake or a single
            mis-keyed truth-table costs an EPROM cycle and a UV-eraser
            session before the next attempt can even boot.
          </p>
        </>
      ),
    },
    {
      kind: "panel",
      variant: "warm",eyebrow: "Tujuh lapisan",heading: "ISO / OSI dari fisik ke atas",
      body: (
        <>
          <p>
            The{" "}
            <Link href="https://en.wikipedia.org/wiki/OSI_model" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
              ISO/OSI 7-layer model
            </Link>
            {" "}— Physical, Data Link, Network, Transport, Session,
            Presentation, Application — was the canonical way to think
            about networking in 1990. Most production stacks
            implemented some subset and pragmatically collapsed
            adjacent layers. Implementing all seven cleanly on a
            single 8-bit MCU with no operating system meant carrying
            every layer's state in a hand-rolled buffer scheme,
            interleaving timers and UART interrupts, and never
            allocating memory the system couldn't statically prove was
            safe.
          </p>
          <figure className="my-6 rounded-xl border border-border/40 bg-card/30 p-5">
            <svg viewBox="0 0 720 320" className="w-full h-auto" role="img" aria-labelledby="osi-stack-title">
              <title id="osi-stack-title">ISO/OSI 7-layer stack on HC11</title>
              <g fontFamily="ui-sans-serif,system-ui" fontSize="12">
                {[
                  ["Application", "L7", "the user's protocol semantics", "hsl(280 60% 65%)"],
                  ["Presentation", "L6", "encoding / framing of values", "hsl(220 60% 65%)"],
                  ["Session", "L5", "dialog state · turn-taking", "hsl(195 60% 60%)"],
                  ["Transport", "L4", "reliable delivery · windowing", "hsl(140 55% 55%)"],
                  ["Network", "L3", "addressing · routing", "hsl(80 60% 55%)"],
                  ["Data Link", "L2", "frame · CRC · UART driver", "hsl(40 70% 55%)"],
                  ["Physical", "L1", "wire · UART hardware · timing", "hsl(20 70% 60%)"],
                ].map(([name, L, note, color], i) => {
                  const y = 24 + i * 38;
                  return (
                    <g key={i}>
                      <rect x="60" y={y} width="600" height="32" rx="6" fill="hsl(220 25% 16%)" stroke={String(color)} />
                      <text x="78" y={y + 21} fill={String(color)} fontSize="11" fontFamily="ui-monospace">{String(L)}</text>
                      <text x="120" y={y + 21} fill={String(color)} fontSize="13" fontWeight="500">{String(name)}</text>
                      <text x="320" y={y + 21} fill="hsl(220 30% 70%)" fontSize="10">{String(note)}</text>
                    </g>
                  );
                })}
              </g>
            </svg>
            <figcaption className="text-xs text-muted-foreground mt-3 text-center">
              Seven layers, all running on a single 8-bit MCU with
              hand-rolled memory discipline, interrupt-driven UART
              service at the bottom and the application protocol
              semantics at the top.
            </figcaption>
          </figure>
          <p>
            The pattern that came out of this — every layer
            addressable, every layer doing exactly its job, no layer
            collapsing into another — is the architectural conviction
            that thirty-six years later still organises the{" "}
            <Link href="/people/coherence-network" className="text-primary hover:underline">
              Coherence Network
            </Link>
            's data layers (graph / API / web / spectrum-coloured
            edges). The vocabulary changed; the discipline didn't.
          </p>
        </>
      ),
    },
    {
      kind: "narrative",heading: "Membangun debugger yang tidak ada",
      body: (
        <>
          <p>
            The hardest detail in the user's own description: <em>"I
            had to write my own debugger"</em>. In 1990 a Motorola
            HC11 bring-up rig in a lift-engineering shop in
            Switzerland came with a power supply, a serial cable, and
            very little else. Commercial in-circuit emulators existed
            but were the price of a small car; what shipped with the
            development kit was a thin monitor program, not a real
            debugger. So one had to be written.
          </p>
          <p>
            Writing a debugger before you have a debugger is the kind
            of recursive bootstrap that makes the conviction stick.
            The first version of the debugger was probably a few
            instructions burned to EPROM that lit an LED in a known
            sequence; the second was a serial monitor that could dump
            registers; the third — the working one — could set
            breakpoints by replacing instructions with a software
            interrupt and stepping into them. Every layer of the tool
            had to come up before the layer above it could be tested
            at all. The breath of <em>build the tool you need</em>{" "}
            became muscle memory here.
          </p>
          <p>
            Twenty-six years later this body would name the same
            posture in a thesis: <em>"every BMA instruction has a
            forward and a reverse semantics; the architecture is
            symmetric"</em>. The 1990 HC11 work was the first time
            this body learned that the system you build can be the
            tool you use to build it. That posture is now spelled out
            in this network's commit verbs —{" "}
            <code className="text-foreground/80">tend</code> /{" "}
            <code className="text-foreground/80">attune</code> /{" "}
            <code className="text-foreground/80">compost</code> /{" "}
            <code className="text-foreground/80">release</code> — as
            the same self-referential discipline.
          </p>
        </>
      ),
    },
    {
      kind: "panel",
      variant: "cool",eyebrow: "Apa karya ini disemen",heading: "Convictions that ride forward",
      body: (
        <ul className="space-y-2 list-disc list-inside marker:text-muted-foreground">
          <li>
            <strong>Every layer is addressable.</strong> The 7-layer
            stack made this discipline early. Re-emerges in BML's
            grammar-in-grammar, the Quark Virtual DOM, the
            Coherence-Network's seven edge-type families.
          </li>
          <li>
            <strong>Build the tool you need, all the way down.</strong>{" "}
            From the custom debugger forward to writing a parser,
            compiler-compiler, virtual machine, undo engine, test
            harness, and now an entire idea-realization network.
          </li>
          <li>
            <strong>Hardware-level discipline at every altitude.</strong>{" "}
            What you allocate on an HC11, you must prove safe. Same
            posture in the Quark undo engine where every action had
            to know its blast radius, in the Qualcomm test harness
            where every test was real C# rather than a JSON manifest,
            in this network's auto-attune where every claim is
            traceable.
          </li>
          <li>
            <strong>C as native tongue.</strong> Learned here, carried
            into the BML implementation (BMCPU was C++ on a C-host),
            QuarkXPress (C++ with COM), early Qualcomm
            (Windows/Graphics divisions). The substrate for two
            decades of system-level work.
          </li>
        </ul>
      ),
    },
  ],
  footer: (
    <p>
      Source materials are pre-digital and not in the public archive.
      What lives here is the architectural shape, the user's own
      framing, and what is honestly knowable from the body's lived
      memory of building it. The HC11 itself is documented at{" "}
      <Link href="https://en.wikipedia.org/wiki/Motorola_68HC11" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
        Wikipedia · Motorola 68HC11
      </Link>
      ; ISO/OSI 7-layer at{" "}
      <Link href="https://en.wikipedia.org/wiki/OSI_model" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
        Wikipedia · OSI model
      </Link>
      . Urs is invited to refine any technical detail or the exact
      year-range through the Refine doorway below.
    </p>
  ),
};

export default content;
