// ════════════════════════════════════════════════════════════════════
// MASCHINELL ÜBERSETZT · machine-translated from en.tsx
// Generated by scripts/generate_curated_translations.py via libretranslate.
// JSX structure preserved via placeholder-tag pre/post processing.
// Refinement welcome — replace any line with author-curated prose at
// any time; the locale-router will pick this file up automatically.
// To regenerate: python3 scripts/generate_curated_translations.py \
//                  --slug quark-virtual-dom --target-lang id
// ════════════════════════════════════════════════════════════════════
import Link from "next/link";
import type { PersonProfileContent } from "@/components/people/PersonProfileTemplate";

const content: PersonProfileContent = {
  metadata: {title: "Quark Virtual DOM - aplikasi API sebagai pohon DOM hidup",description: "Sementara di Quark di Denver, Urs dirancang dan dikirim DOM virtual yang mengekspos seluruh QuarkXPress API sebagai pohon dokumen hidup. Setiap konfigurasi, setiap dokumen, setiap kotak, setiap atribut menjadi titik DOM yang dapat diubah oleh klien DOM standar - baca atau tulis bagian apapun dari aplikasi yang berjalan tanpa lapisan pengikatan gubahan.",
  },breadcrumbName: "Quark Virtual DOM",
  hero: {
    background:
      "linear-gradient(135deg, hsl(220 30% 8%), hsl(195 35% 14%) 50%, hsl(280 30% 16%))",
    overlayClass:
      "absolute inset-0 bg-gradient-to-t from-background via-background/85 to-background/30",eyebrow: "Bekerja",
    eyebrowClass: "text-[hsl(var(--chart-2))]",name: "Quark Virtual DOM",
    welcome: (
      <p>
        A virtual DOM exposing the entire QuarkXPress API. Every
        application setting, every open document, every page, every
        text box, every measurement — addressable as a node in a
        standard DOM tree. A scripting client could read or write
        any part of the running application without a custom
        per-feature binding. Years before the browser-side virtual-
        DOM idea entered the public conversation, the same shape was
        running production at Quark — applied to a desktop publisher
        instead of a web view.
      </p>
    ),
  },
  facts: [
    {label: "Era",value: "Quark Inc. Kantor di Denver 2000 Mei 2005" },
    {label: "Substrat",value: "C + +" },
    {label: "Aplikasi", value: (<>QuarkXPress — the desktop publishing application that defined a generation of print and layout work. <Link href="https://www.quark.com" target="_blank" rel="noopener noreferrer" className="hover:text-primary">quark.com</Link></>) },
    {label: "Garis Keturunan kembali",
      value: (
        <>
          Carries forward the self-describing posture from the{" "}
          <Link href="/people/bml-language" className="hover:text-primary">2000 BML thesis</Link>
          {" "}— a system that describes its own structure to itself.
          BML's grammar parsed itself; the Quark Virtual DOM made
          QuarkXPress query and mutate itself.
        </>
      ),
    },
    {label: "Garis Keturunan kedepan",
      value: (
        <>
          The everything-is-a-node primitive that became U-CORE in{" "}
          <Link href="/people/living-codex-csharp" className="hover:text-primary">Living-Codex-CSharp</Link>
          {" "}and the live-graph data layer in{" "}
          <Link href="/people/coherence-network" className="hover:text-primary">Coherence-Network</Link>
          {" "}is the same conviction at network scale — the Quark
          Virtual DOM was the desktop-app form of the same idea.
        </>
      ),
    },
  ],
  noteFromBody: {eyebrow: "Mengapa ini di sini",
    body: (
      <p>
        Two design choices the Quark years committed to ride forward
        through every later iteration:{" "}
        <strong>self-description as architecture</strong> — the system
        is its own API surface — and <strong>universal addressing</strong>{" "}
        — every part of state has a path. They show up in BML (2000)
        as the grammar-in-grammar, in this Quark Virtual DOM as the
        application-in-DOM, in U-CORE as Everything-is-a-Node, and in
        Coherence-Network as the graph-of-presences. One conviction;
        four substrates.
      </p>
    ),
  },
  articles: [
    {
      kind: "narrative",heading: "Bentuk API",
      body: (
        <>
          <p>
            The conventional way to expose a desktop application's API
            in 2000-era C++ was binding-per-feature: one C function or
            COM method for each thing the API needed to surface, hand-
            written, hand-versioned, exposed through a SDK. AppleScript
            on the Mac side, COM Automation on the Windows side. Every
            new feature meant a new pair of bindings. The surface area
            grew faster than the team's capacity to keep it consistent.
          </p>
          <p>
            The Quark Virtual DOM took the opposite turn. Instead of
            exposing N APIs, it exposed{" "}
            <em>one</em> API — the standard DOM interface — and made
            every application object reachable as a DOM node. The
            running application became a live tree. Settings,
            documents, pages, text boxes, picture boxes, style sheets,
            colors, hyphenation rules — each appeared as a node with
            attributes, children, and the standard DOM operations
            (<code className="text-foreground/80">getElementById</code>,{" "}
            <code className="text-foreground/80">setAttribute</code>,{" "}
            <code className="text-foreground/80">appendChild</code>) acting on
            real application state.
          </p>
          <figure className="my-6 rounded-xl border border-border/40 bg-card/30 p-5">
            <svg viewBox="0 0 720 320" className="w-full h-auto" role="img" aria-labelledby="qdom-arch-title">
              <title id="qdom-arch-title">Quark Virtual DOM architecture</title>
              <g fontFamily="ui-sans-serif,system-ui" fontSize="12">
                {/* Top: Clients */}
                <rect x="60" y="20" width="600" height="44" rx="10" fill="hsl(220 25% 18%)" stroke="hsl(195 60% 60%)" />
                <text x="80" y="42" fill="hsl(195 80% 80%)" fontSize="13">Standard DOM clients</text>
                <text x="80" y="58" fill="hsl(195 50% 70%)" fontSize="10">automation scripts · plug-ins · third-party tools · QA harnesses · headless test runners</text>

                <line x1="360" y1="64" x2="360" y2="80" stroke="hsl(220 30% 60%)" strokeWidth="1.5" />

                {/* Middle: Virtual DOM layer */}
                <rect x="60" y="80" width="600" height="100" rx="10" fill="hsl(195 35% 16%)" stroke="hsl(195 70% 60%)" strokeWidth="2" />
                <text x="80" y="106" fill="hsl(195 90% 85%)" fontSize="14" fontWeight="500">Virtual DOM Layer</text>
                <text x="80" y="124" fill="hsl(195 60% 75%)" fontSize="11">node ↔ application-object resolver · attribute getter/setter dispatch</text>
                <text x="80" y="140" fill="hsl(195 60% 75%)" fontSize="11">dynamic node creation on traversal · lazy materialization · change notification</text>
                <text x="80" y="156" fill="hsl(195 60% 75%)" fontSize="11">document-context aware · type-tagged · path-addressable</text>
                <text x="80" y="172" fill="hsl(195 50% 70%)" fontSize="10">/quarkxpress/preferences/measurements/units = "points"  →  app-wide setting write</text>

                <line x1="240" y1="180" x2="240" y2="200" stroke="hsl(220 30% 60%)" strokeWidth="1.5" />
                <line x1="480" y1="180" x2="480" y2="200" stroke="hsl(220 30% 60%)" strokeWidth="1.5" />

                {/* Bottom: real app state */}
                <rect x="60" y="200" width="280" height="80" rx="10" fill="hsl(220 25% 16%)" stroke="hsl(40 70% 55%)" />
                <text x="80" y="226" fill="hsl(40 90% 80%)" fontSize="13">Application state · global</text>
                <text x="80" y="244" fill="hsl(40 50% 70%)" fontSize="10">preferences · hyphenation · color-management · plug-in registry</text>
                <text x="80" y="260" fill="hsl(40 50% 70%)" fontSize="10">window manager · undo manager · clipboard</text>

                <rect x="380" y="200" width="280" height="80" rx="10" fill="hsl(220 25% 16%)" stroke="hsl(280 50% 60%)" />
                <text x="400" y="226" fill="hsl(280 80% 80%)" fontSize="13">Document state · per-document</text>
                <text x="400" y="244" fill="hsl(280 50% 70%)" fontSize="10">pages · spreads · master pages · style sheets</text>
                <text x="400" y="260" fill="hsl(280 50% 70%)" fontSize="10">text boxes · picture boxes · groups · layers · runs</text>

                <text x="360" y="305" fill="hsl(220 30% 65%)" textAnchor="middle" fontSize="11" fontStyle="italic">
                  one DOM tree · two state realms · live read and write
                </text>
              </g>
            </svg>
            <figcaption className="text-xs text-muted-foreground mt-3 text-center">
              Standard DOM clients on top, the virtual-DOM resolver in
              the middle, real C++ application state at the bottom —
              with the tree spanning both the global app realm and the
              per-document realm.
            </figcaption>
          </figure>
          <p>
            From a script's perspective there was nothing virtual about
            it. It was a real DOM. From the runtime's perspective, the
            tree didn't exist — it was materialized lazily on traversal,
            so a script that asked for{" "}
            <code className="text-foreground/80">documents[0].pages[3].boxes[7].font</code>
            {" "}only paid for the path it walked. The full application
            state was never serialized into nodes; the nodes were
            <em>views</em> on the state.
          </p>
        </>
      ),
    },
    {
      kind: "panel",
      variant: "cool",eyebrow: "Contoh",heading: "QuarkXPress sebagai pohon",
      body: (
        <>
          <p>
            A script using nothing more than the standard DOM
            interface — the same shape any web developer was already
            fluent in — could now drive a desktop publisher:
          </p>
          <pre className="text-[11px] leading-5 bg-background/60 border border-border/40 rounded-lg p-4 overflow-x-auto font-mono">
{`// Read an application-wide preference
const units = xpressDom
  .getElementById('preferences')
  .getAttribute('measurements/units');

// Walk the document tree
const docs = xpressDom.documentElement.children;          // open documents
const firstDoc = docs[0];
const page3 = firstDoc.querySelector('page[index="3"]');
const titleBox = page3.querySelector('text-box[role="title"]');

// Mutate live state — change is reflected immediately
titleBox.setAttribute('font-family', 'Adobe Caslon Pro');
titleBox.setAttribute('font-size', '24pt');
titleBox.firstChild.textContent = 'New headline';

// Listen for changes anyone makes (script, user, plug-in)
firstDoc.addEventListener('attribute-changed', (e) => {
   console.log(e.target.path, e.detail.attr, e.detail.from, e.detail.to);
});`}
          </pre>
          <p>
            Standard idioms — <code className="text-foreground/80">getElementById</code>,{" "}
            <code className="text-foreground/80">querySelector</code>,{" "}
            <code className="text-foreground/80">setAttribute</code>,{" "}
            <code className="text-foreground/80">addEventListener</code> —
            performing real desktop-app operations. A QA harness could
            drive QuarkXPress through arbitrary keystrokes by setting
            attributes. A plug-in could register for change events on
            any path. An external automation tool could open a document,
            edit ten boxes, save, and exit — without a single
            QuarkXPress-specific API call.
          </p>
        </>
      ),
    },
    {
      kind: "narrative",heading: "Mengapa ini sulit",
      body: (
        <>
          <p>
            The shape is elegant; the implementation was load-bearing.
            Three things had to be true at once:
          </p>
          <ul className="space-y-2 list-disc list-inside marker:text-muted-foreground">
            <li>
              <strong>Lazy materialization.</strong> A QuarkXPress
              document with hundreds of pages and thousands of objects
              cannot have all those nodes pre-allocated. Nodes had to
              materialize on traversal — a child request walked into the
              underlying C++ object graph and minted the node on demand.
              GC of unreferenced nodes had to happen invisibly.
            </li>
            <li>
              <strong>Bi-directional change propagation.</strong> A
              script's <code className="text-foreground/80">setAttribute</code>{" "}
              had to land in the real C++ state and trigger every
              redraw, undo-record, and document-changed notification a
              user-driven equivalent action would. Symmetrically, a
              user dragging a box had to make the corresponding DOM
              attributes update so any listening script saw the change.
            </li>
            <li>
              <strong>Type-tagged dynamic schema.</strong> Every node
              kind had its own attribute set; the resolver had to know
              what attributes were valid on{" "}
              <code className="text-foreground/80">text-box</code> versus{" "}
              <code className="text-foreground/80">picture-box</code>,
              what type each attribute carried (point, color, font
              identifier, percentage), how to coerce string values
              the DOM API enforced. Dynamic creation of nodes and
              attributes meant the schema had to be queryable from the
              API too — the DOM described its own shape.
            </li>
          </ul>
          <p>
            That last point is the deep one. The tree wasn't a fixed
            DTD. New plug-ins added new node kinds. New document
            features grew the attribute vocabulary. The Virtual DOM
            had to stay self-describing — clients could ask the tree
            what it could do, and the tree would answer. That's the
            same posture the{" "}
            <Link href="/people/bml-language" className="text-primary hover:underline">
              2000 BML thesis
            </Link>
            {" "}committed to with grammar-in-grammar — and the same
            posture that, twenty-some years later,{" "}
            <Link href="/people/coherence-network" className="text-primary hover:underline">
              Coherence-Network
            </Link>
            {" "}now lives at the network scale.
          </p>
        </>
      ),
    },
    {
      kind: "panel",
      variant: "warm",eyebrow: "Pembacaan sejarah",heading: "Tahun sebelum percakapan peramban",
      body: (
        <p>
          The phrase <em>virtual DOM</em> entered the public
          vocabulary mostly through React, around 2013. By that point
          the same architectural pattern — a virtual tree fronting a
          mutable state graph, with bidirectional change propagation —
          had been running in QuarkXPress production for nearly a
          decade. Different problem (desktop publishing rather than
          UI rendering), different substrate (C++ on Mac/Windows
          rather than JavaScript in a browser), but the same
          architectural turn. This page exists in part to write the
          desktop-application form of the pattern back into the public
          record where it was first lived.
        </p>
      ),
    },
  ],
  footer: (
    <p>
      Application context:{" "}
      <Link
        href="https://www.quark.com"
        target="_blank"
        rel="noopener noreferrer"
        className="text-primary hover:underline"
      >
        quark.com
      </Link>
      {" · "}
      <Link
        href="https://en.wikipedia.org/wiki/QuarkXPress"
        target="_blank"
        rel="noopener noreferrer"
        className="text-primary hover:underline"
      >
        QuarkXPress on Wikipedia
      </Link>
      . Source code is internal to Quark and not public; the substance
      above is the architectural shape, the design rationale, and the
      lived memory of building it. Urs is invited to refine any
      technical detail through the Refine doorway below.
    </p>
  ),
};

export default content;
